packages:
    - "apps/*"
    - "examples/*"
    - "packages/*"
    - "extensions/*"

catalog:
    "@effect/opentelemetry": "4.0.0-beta.98"
    "@effect/vitest": "4.0.0-beta.98"
    "@opentelemetry/api": "^1.9.0"
    "@opentelemetry/api-logs": "^0.205.0"
    "@opentelemetry/resources": "^2.2.0"
    "@opentelemetry/sdk-logs": "^0.205.0"
    "@opentelemetry/sdk-metrics": "^2.2.0"
    "@opentelemetry/sdk-trace-base": "^2.2.0"
    "@opentelemetry/sdk-trace-node": "^2.2.0"
    "@opentelemetry/sdk-trace-web": "^2.2.0"
    "@opentelemetry/semantic-conventions": "^1.38.0"
    "@stylexjs/rollup-plugin": "^0.19.0"
    "@stylexjs/stylex": "^0.19.0"
    "effect": "4.0.0-beta.98"
    "solid-js": "^1.9.14"
    "vite-plugin-solid": "^2.11.12"

onlyBuiltDependencies:
    - electron
    - esbuild
