import type {
	BlueprintGraph,
	BlueprintGraphProjection,
	BlueprintNode,
	BlueprintPin
} from "@ue-shed/protocol";
import { describe, expect, it } from "vitest";
import {
	blueprintLinkPath,
	blueprintNeighbors,
	blueprintNodeDisplay,
	blueprintPinDefaults,
	blueprintPinFlags,
	blueprintPinTypeLabel,
	findBlueprintPin,
	indexBlueprintGraph,
	isBlueprintTopologyGap,
	layoutBlueprintGraph,
	MAX_BLUEPRINT_SEARCH_HITS,
	searchBlueprint
} from "./index.js";

function pin(id: string, direction: "input" | "output" = "input"): BlueprintPin {
	return {
		id,
		name: id,
		direction,
		source_index: 0,
		tooltip: "",
		flags: 0,
		default_value: "",
		autogenerated_default_value: "",
		linked_to: [],
		sub_pins: [],
		pin_type: {
			category: "exec",
			subcategory: "",
			container_type: "none",
			is_reference: false,
			is_weak_pointer: false,
			member_reference: { name: "" },
			is_const: false,
			is_uobject_wrapper: false,
			serialize_as_single_precision_float: false
		}
	};
}

function node(path: string, pins: readonly BlueprintPin[] = []): BlueprintNode {
	return {
		object_path: path,
		class_path: "/Script/BlueprintGraph.K2Node_CallFunction",
		kind: "function_call",
		title: path,
		position: { x: -100, y: -200 },
		properties: [],
		pins,
		subclass_tail_bytes: 0
	};
}

function graph(nodes: readonly BlueprintNode[]): BlueprintGraph {
	return { object_path: "/Game/BP.BP.EventGraph", name: "EventGraph", nodes, links: [] };
}

function blueprint(graphs: readonly BlueprintGraph[]): BlueprintGraphProjection {
	return {
		schema_version: 2,
		object_path: "/Game/BP.BP",
		graphs,
		coverage_gaps: [],
		definition: {
			parent_class: null,
			variables: null,
			default_object: null,
			construction_script: null
		}
	};
}

describe("saved Blueprint tools", () => {
	it("resolves pins by owner even when IDs repeat on different nodes", () => {
		const a = node("a", [pin("same")]);
		const b = node("b", [pin("same")]);
		const index = indexBlueprintGraph(graph([a, b]));
		expect(findBlueprintPin(index, { node_object_path: "b", pin_id: "same" })).toBe(b.pins[0]);
		expect(findBlueprintPin(index, { pin_id: "same" })).toBeUndefined();
		expect(
			findBlueprintPin(index, { node_object_path: "missing", pin_id: "same" })
		).toBeUndefined();
	});

	it("reports ambiguous nodes and pins without choosing a duplicate", () => {
		const index = indexBlueprintGraph(
			graph([node("a", [pin("p"), pin("p"), pin("p")]), node("b"), node("b"), node("b")])
		);
		expect(index.issues).toEqual([
			{ reason: "duplicate_pin_id", nodeObjectPath: "a", pinId: "p" },
			{ reason: "duplicate_node_path", nodeObjectPath: "b", pinId: null }
		]);
		expect(index.nodes.has("b")).toBe(false);
		expect(findBlueprintPin(index, { node_object_path: "a", pin_id: "p" })).toBeUndefined();
	});

	it("navigates saved links in order while retaining cycles and skipping unavailable endpoints", () => {
		const value = graph([
			node("a", [pin("out", "output"), pin("in")]),
			node("b", [pin("in"), pin("out", "output")])
		]);
		const ab = {
			from: { node_object_path: "a", pin_id: "out" },
			to: { node_object_path: "b", pin_id: "in" }
		};
		const ba = {
			from: { node_object_path: "b", pin_id: "out" },
			to: { node_object_path: "a", pin_id: "in" }
		};
		const index = indexBlueprintGraph({
			...value,
			links: [ab, ab, ba, { ...ab, to: { pin_id: "missing" } }]
		});
		for (const direction of ["incoming", "outgoing", "both"] as const) {
			expect(
				blueprintNeighbors({ index, direction, nodeObjectPath: "a" }).map(
					(item) => item.object_path
				)
			).toEqual(["b"]);
		}
		expect(blueprintNeighbors({ index, direction: "both", nodeObjectPath: "missing" })).toEqual(
			[]
		);
	});

	it("normalizes negative coordinates and connects pins without changing saved positions", () => {
		const a = node("a", [pin("out", "output")]);
		const b = { ...node("b", [pin("in")]), position: { x: 260, y: -200 } };
		const layout = layoutBlueprintGraph(graph([a, b]));
		expect(layout.nodes.get("a")?.x).toBe(72);
		expect(layout.nodes.get("b")?.x).toBeCloseTo(367.2);
		expect(a.position).toEqual({ x: -100, y: -200 });
		expect(
			blueprintLinkPath(layout, {
				from: { node_object_path: "a", pin_id: "out" },
				to: { node_object_path: "b", pin_id: "in" }
			})
		).toMatch(/^M 340 127.5 C /);
		expect(
			blueprintLinkPath(layout, {
				from: { pin_id: "out" },
				to: { node_object_path: "b", pin_id: "in" }
			})
		).toBeUndefined();
		expect(layoutBlueprintGraph(undefined).nodes.size).toBe(0);
	});

	it("keeps ambiguous pins out of geometry", () => {
		const layout = layoutBlueprintGraph(graph([node("a", [pin("p"), pin("p")])]));
		expect(layout.pinPoints.get("a")?.size).toBe(0);
	});

	it("formats map terminals and distinguishes explicit empty text from omitted defaults", () => {
		const value = pin("map");
		const typed: BlueprintPin = {
			...value,
			pin_type: {
				...value.pin_type,
				category: "name",
				container_type: "map",
				is_const: true,
				is_reference: true,
				value_type: {
					category: "object",
					subcategory: "",
					subcategory_object: "/Script/Engine.Actor",
					is_const: false,
					is_weak_pointer: false,
					is_uobject_wrapper: false
				}
			}
		};
		expect(blueprintPinTypeLabel(typed)).toBe("const ref map<name → object · Actor>");
		expect(blueprintPinDefaults(value)).toEqual([]);
		expect(blueprintPinDefaults({ ...value, default_text_value: { source: "" } })).toEqual([
			{ label: "Text default", value: "" }
		]);
	});

	it("decodes persistent archive flags and retains unknown bits", () => {
		const flags = blueprintPinFlags({ ...pin("p"), flags: 0x800000ff });
		expect(flags).toEqual({
			hidden: true,
			notConnectable: true,
			defaultReadOnly: true,
			defaultIgnored: true,
			advanced: true,
			orphaned: true,
			hasSnappedChild: true,
			hasSnappedParent: true,
			unknownBits: 0x80000000
		});
		expect(blueprintPinFlags(pin("p")).hidden).toBe(false);
	});

	it("preserves absent, false and empty display evidence and refuses duplicate properties", () => {
		const display = blueprintNodeDisplay({
			...node("a"),
			properties: [
				{ name: "NodeComment", type: "StrProperty", value_kind: "string", value: "" },
				{ name: "NodeWidth", type: "IntProperty", value_kind: "int", value: 640 },
				{
					name: "bCommentBubbleVisible",
					type: "BoolProperty",
					value_kind: "bool",
					value: false
				}
			]
		});
		expect(display).toEqual({
			comment: "",
			width: 640,
			height: null,
			commentBubbleVisible: false,
			commentBubblePinned: null,
			enabledState: null
		});
		expect(
			blueprintNodeDisplay({
				...node("a"),
				properties: [
					{ name: "NodeWidth", type: "IntProperty", value_kind: "int", value: 1 },
					{ name: "NodeWidth", type: "IntProperty", value_kind: "int", value: 2 }
				]
			}).width
		).toBeNull();
	});

	it("searches literal terms across graphs, comments, friendly pins and Unicode defaults", () => {
		const a = {
			...node("a", [
				{
					...pin("p"),
					friendly_name: { source: "Friendly pin" },
					default_text_value: { source: "世界 🌟" },
					autogenerated_default_value: "generated-marker",
					pin_type: {
						...pin("p").pin_type,
						category: "object",
						subcategory_object: "/Script/Engine.Actor"
					}
				}
			]),
			properties: [
				{
					name: "NodeComment",
					type: "StrProperty",
					value_kind: "string" as const,
					value: "Review [comment]"
				}
			]
		};
		const input = blueprint([
			graph([a]),
			{ ...graph([node("b")]), name: "Utility", object_path: "utility" }
		]);
		expect(
			searchBlueprint({ blueprint: input, query: "friendly 世界" }).hits.map(
				(hit) => hit.pinId
			)
		).toEqual(["p"]);
		for (const query of ["generated-marker", "/Script/Engine.Actor"]) {
			expect(
				searchBlueprint({ blueprint: input, query }).hits.map((hit) => hit.pinId)
			).toEqual(["p"]);
		}
		expect(
			searchBlueprint({ blueprint: input, query: "[COMMENT]" }).hits.map((hit) => hit.kind)
		).toEqual(["node"]);
		expect(
			searchBlueprint({ blueprint: input, query: "utility" }).hits[0]?.graphObjectPath
		).toBe("utility");
		expect(searchBlueprint({ blueprint: input, query: "  " }).hits).toEqual([]);
	});

	it("bounds search output without silently claiming all results", () => {
		const nodes = Array.from({ length: MAX_BLUEPRINT_SEARCH_HITS + 1 }, (_, i) =>
			node(`match${i}`)
		);
		const result = searchBlueprint({ blueprint: blueprint([graph(nodes)]), query: "match" });
		expect(result.hits).toHaveLength(MAX_BLUEPRINT_SEARCH_HITS);
		expect(result.truncated).toBe(true);
		expect(
			searchBlueprint({ blueprint: blueprint([graph(nodes.slice(0, -1))]), query: "match" })
				.truncated
		).toBe(false);
	});

	it("keeps definition and opaque metadata gaps distinct from missing topology", () => {
		for (const reason of [
			"native_node_subclass_tail",
			"undecoded_node_property",
			"incomplete_definition"
		] as const) {
			expect(isBlueprintTopologyGap({ reason, object_path: "a", detail: "" })).toBe(false);
		}
		expect(
			isBlueprintTopologyGap({
				reason: "unresolved_linked_pin",
				object_path: "a",
				detail: ""
			})
		).toBe(true);
	});
});
