import type { BlueprintNode, BlueprintPin, SavedProperty } from "@ue-shed/protocol";

export type BlueprintPinTone =
	| "boolean"
	| "exec"
	| "numeric"
	| "object"
	| "struct"
	| "text"
	| "wildcard";

export function blueprintClassLabel(classPath: string): string {
	return (
		classPath
			.split(".")
			.at(-1)
			?.replace(/^K2Node_/, "") ?? classPath
	);
}

export function blueprintPinLabel(pin: BlueprintPin): string {
	return pin.friendly_name?.source || pin.name || "unnamed";
}

export function blueprintPinTone(pin: BlueprintPin | undefined): BlueprintPinTone {
	const category = pin?.pin_type.category.toLowerCase() ?? "";
	if (category === "exec") return "exec";
	if (category === "bool" || category === "boolean") return "boolean";
	if (["byte", "double", "float", "int", "int64", "real"].includes(category)) return "numeric";
	if (["name", "string", "text"].includes(category)) return "text";
	if (["class", "interface", "object", "softclass", "softobject"].includes(category))
		return "object";
	return category === "struct" ? "struct" : "wildcard";
}

function terminalLabel(type: {
	readonly category: string;
	readonly subcategory: string;
	readonly subcategory_object?: string;
}): string {
	return [type.category, type.subcategory || type.subcategory_object?.split(".").at(-1)]
		.filter((value): value is string => value !== undefined && value !== "")
		.join(" · ");
}

export function blueprintPinTypeLabel(pin: BlueprintPin): string {
	const type = pin.pin_type;
	const base = terminalLabel(type);
	const contained =
		type.container_type === "map" && type.value_type !== undefined
			? base + " → " + terminalLabel(type.value_type)
			: base;
	const container =
		type.container_type === "none" ? contained : type.container_type + "<" + contained + ">";
	const modifiers = [type.is_const ? "const" : undefined, type.is_reference ? "ref" : undefined]
		.filter((value): value is string => value !== undefined)
		.join(" ");
	return modifiers === "" ? container || "wildcard" : modifiers + " " + (container || "wildcard");
}

export function blueprintPinDefaults(
	pin: BlueprintPin
): readonly { readonly label: string; readonly value: string }[] {
	const defaults: Array<{ readonly label: string; readonly value: string }> = [];
	if (pin.default_text_value !== undefined)
		defaults.push({ label: "Text default", value: pin.default_text_value.source });
	if (pin.default_object !== undefined)
		defaults.push({ label: "Object default", value: pin.default_object });
	if (pin.default_value !== "")
		defaults.push({ label: "Saved default", value: pin.default_value });
	if (pin.autogenerated_default_value !== "")
		defaults.push({ label: "Generated default", value: pin.autogenerated_default_value });
	return defaults;
}

/** Persistent archive bits verified in EdGraphPin.cpp on UE 5.7 and 5.8, not C++ memory bitfields. */
export function blueprintPinFlags(pin: BlueprintPin) {
	const flags = pin.flags;
	return {
		hidden: (flags & 1) !== 0,
		notConnectable: (flags & 2) !== 0,
		defaultReadOnly: (flags & 4) !== 0,
		defaultIgnored: (flags & 8) !== 0,
		advanced: (flags & 16) !== 0,
		orphaned: (flags & 32) !== 0,
		hasSnappedChild: (flags & 64) !== 0,
		hasSnappedParent: (flags & 128) !== 0,
		unknownBits: (flags & ~255) >>> 0
	};
}

function uniqueProperty(node: BlueprintNode, name: string): SavedProperty | undefined {
	let result: SavedProperty | undefined;
	for (const property of node.properties) {
		if (property.name !== name) continue;
		if (result !== undefined) return undefined;
		result = property;
	}
	return result;
}

/** Missing or undecoded properties remain null rather than inferred editor defaults. */
export function blueprintNodeDisplay(node: BlueprintNode) {
	const string = (name: string) => {
		const value = uniqueProperty(node, name);
		return value?.value_kind === "string" ? value.value : null;
	};
	const integer = (name: string) => {
		const value = uniqueProperty(node, name);
		return value?.value_kind === "int" || value?.value_kind === "uint" ? value.value : null;
	};
	const bool = (name: string) => {
		const value = uniqueProperty(node, name);
		return value?.value_kind === "bool" ? value.value : null;
	};
	const enabled = uniqueProperty(node, "EnabledState");
	return {
		comment: string("NodeComment"),
		width: integer("NodeWidth"),
		height: integer("NodeHeight"),
		commentBubbleVisible: bool("bCommentBubbleVisible"),
		commentBubblePinned: bool("bCommentBubblePinned"),
		enabledState: enabled?.value_kind === "enum" ? enabled.value : null
	};
}
