import type { BlueprintGraphProjection } from "@ue-shed/protocol";
import { blueprintNodeDisplay, blueprintPinLabel, blueprintPinTypeLabel } from "./presentation.js";

export interface BlueprintSearchHit {
	readonly kind: "node" | "pin";
	readonly graphObjectPath: string;
	readonly nodeObjectPath: string;
	readonly pinId: string | null;
	readonly label: string;
}

export const MAX_BLUEPRINT_SEARCH_HITS = 500;

export interface BlueprintSearchResult {
	readonly hits: readonly BlueprintSearchHit[];
	readonly truncated: boolean;
}

/** Literal, case-insensitive search in saved order; every whitespace-separated term must match. */
export function searchBlueprint(input: {
	readonly blueprint: BlueprintGraphProjection;
	readonly query: string;
}): BlueprintSearchResult {
	const terms = input.query.trim().toLowerCase().split(/\s+/).filter(Boolean);
	const hits: BlueprintSearchHit[] = [];
	if (terms.length === 0) return { hits, truncated: false };
	const matches = (values: readonly string[]) => {
		const text = values.join("\n").toLowerCase();
		return terms.every((term) => text.includes(term));
	};
	for (const graph of input.blueprint.graphs) {
		for (const node of graph.nodes) {
			const common = [graph.name, node.title, node.class_path, node.object_path];
			if (matches([...common, blueprintNodeDisplay(node).comment ?? ""])) {
				if (hits.length === MAX_BLUEPRINT_SEARCH_HITS) return { hits, truncated: true };
				hits.push({
					kind: "node",
					graphObjectPath: graph.object_path,
					nodeObjectPath: node.object_path,
					pinId: null,
					label: node.title
				});
			}
			for (const pin of node.pins) {
				if (
					!matches([
						...common,
						pin.name,
						blueprintPinLabel(pin),
						blueprintPinTypeLabel(pin),
						pin.pin_type.subcategory_object ?? "",
						pin.pin_type.value_type?.subcategory_object ?? "",
						pin.tooltip,
						pin.default_value,
						pin.autogenerated_default_value,
						pin.default_object ?? "",
						pin.default_text_value?.source ?? ""
					])
				)
					continue;
				if (hits.length === MAX_BLUEPRINT_SEARCH_HITS) return { hits, truncated: true };
				hits.push({
					kind: "pin",
					graphObjectPath: graph.object_path,
					nodeObjectPath: node.object_path,
					pinId: pin.id,
					label: blueprintPinLabel(pin)
				});
			}
		}
	}
	return { hits, truncated: false };
}
