import { cleanup, render, screen, waitFor, within } from "@solidjs/testing-library";
import { userEvent } from "@testing-library/user-event";
import type {
	BlueprintGraphCoverageGap,
	BlueprintGraphProjection,
	BlueprintNode,
	BlueprintPin
} from "@ue-shed/protocol";
import { EffectRuntimeProvider } from "@ue-shed/ui";
import { Effect, Layer, ManagedRuntime } from "effect";
import { afterAll, afterEach, describe, expect, it, vi } from "vitest";
import type {
	BlueprintAssetCandidate,
	BlueprintGraphFailureReason,
	BlueprintGraphReadResult
} from "../shared/ipc-contracts.js";
import { BlueprintGraphViewer } from "./blueprint-graph-viewer.js";
import { WorkbenchRendererError, type WorkbenchRendererClient } from "./workbench-client.js";

const runtime = ManagedRuntime.make(Layer.empty);
const assetPath = "C:/Project/Content/UI/WBP_Settings.uasset";
const indexedSettings: BlueprintAssetCandidate = {
	assetName: "WBP_Settings",
	assetPath,
	className: "WidgetBlueprint",
	packageName: "/Game/UI/WBP_Settings",
	relativePath: "Content/UI/WBP_Settings.uasset"
};
const indexedPlayer: BlueprintAssetCandidate = {
	assetName: "BP_PlayerCharacter",
	assetPath: "C:/Project/Content/Characters/BP_PlayerCharacter.uasset",
	className: "Blueprint",
	packageName: "/Game/Characters/BP_PlayerCharacter",
	relativePath: "Content/Characters/BP_PlayerCharacter.uasset"
};

afterEach(cleanup);
afterAll(() => runtime.dispose());

function pin(input: {
	readonly category?: string;
	readonly defaultValue?: string;
	readonly direction: "input" | "output";
	readonly id: string;
	readonly linkedTo?: BlueprintPin["linked_to"];
	readonly name: string;
}): BlueprintPin {
	return {
		id: input.id,
		name: input.name,
		source_index: 0,
		tooltip: input.name === "bEnabled" ? "Whether the setting is enabled." : "",
		direction: input.direction,
		pin_type: {
			category: input.category ?? "exec",
			subcategory: "",
			container_type: "none",
			is_reference: false,
			is_weak_pointer: false,
			member_reference: { name: "" },
			is_const: false,
			is_uobject_wrapper: false,
			serialize_as_single_precision_float: false
		},
		default_value: input.defaultValue ?? "",
		autogenerated_default_value: "",
		linked_to: input.linkedTo ?? [],
		sub_pins: [],
		flags: 0
	};
}

function node(input: {
	readonly classPath: string;
	readonly kind: BlueprintNode["kind"];
	readonly objectPath: string;
	readonly pins: readonly BlueprintPin[];
	readonly title: string;
	readonly x: number;
	readonly y: number;
}): BlueprintNode {
	return {
		object_path: input.objectPath,
		class_path: input.classPath,
		kind: input.kind,
		title: input.title,
		position: { x: input.x, y: input.y },
		properties: [],
		pins: input.pins,
		subclass_tail_bytes: 0
	};
}

const eventPath = "/Game/UI/WBP_Settings.WBP_Settings:EventGraph.Event";
const callPath = "/Game/UI/WBP_Settings.WBP_Settings:EventGraph.Call";

const blueprint: BlueprintGraphProjection = {
	schema_version: 1,
	object_path: "/Game/UI/WBP_Settings.WBP_Settings",
	coverage_gaps: [],
	graphs: [
		{
			object_path: "/Game/UI/WBP_Settings.WBP_Settings:EventGraph",
			name: "EventGraph",
			nodes: [
				node({
					classPath: "/Script/BlueprintGraph.K2Node_Event",
					kind: "event",
					objectPath: eventPath,
					pins: [
						pin({
							direction: "output",
							id: "event-out",
							linkedTo: [{ node_object_path: callPath, pin_id: "call-in" }],
							name: "then"
						})
					],
					title: "On Clicked",
					x: 0,
					y: 0
				}),
				node({
					classPath: "/Script/BlueprintGraph.K2Node_CallFunction",
					kind: "function_call",
					objectPath: callPath,
					pins: [
						pin({ direction: "input", id: "call-in", name: "execute" }),
						pin({
							category: "bool",
							defaultValue: "true",
							direction: "input",
							id: "enabled",
							name: "bEnabled"
						})
					],
					title: "Apply Settings With A Deliberately Long Saved Node Name",
					x: 360,
					y: 0
				})
			],
			links: [
				{
					from: { node_object_path: eventPath, pin_id: "event-out" },
					to: { node_object_path: callPath, pin_id: "call-in" }
				}
			]
		},
		{
			object_path: "/Game/UI/WBP_Settings.WBP_Settings:UtilityGraph",
			name: "A Utility Graph With A Very Long Saved Name",
			nodes: [
				node({
					classPath: "/Script/BlueprintGraph.K2Node_VariableGet",
					kind: "variable_get",
					objectPath: "/Game/UI/WBP_Settings.WBP_Settings:UtilityGraph.Value",
					pins: [
						pin({ category: "float", direction: "output", id: "value", name: "Value" })
					],
					title: "Saved Value",
					x: -420,
					y: 880
				})
			],
			links: []
		}
	]
};

function ready(projection: BlueprintGraphProjection = blueprint): BlueprintGraphReadResult {
	return {
		assetPath,
		blueprint: projection,
		diagnostics: [],
		outcome: "complete",
		status: "ready"
	};
}

type BlueprintViewerClient = Pick<
	WorkbenchRendererClient,
	"chooseBlueprint" | "chooseProject" | "readBlueprint" | "searchBlueprints"
>;

function renderViewer(client: BlueprintViewerClient) {
	return render(() => (
		<EffectRuntimeProvider runtime={runtime}>
			<BlueprintGraphViewer client={client} />
		</EffectRuntimeProvider>
	));
}

function clientWith(
	overrides: {
		readonly chooseBlueprint?: WorkbenchRendererClient["chooseBlueprint"];
		readonly chooseProject?: WorkbenchRendererClient["chooseProject"];
		readonly readBlueprint?: WorkbenchRendererClient["readBlueprint"];
		readonly searchBlueprints?: WorkbenchRendererClient["searchBlueprints"];
	} = {}
): BlueprintViewerClient {
	return {
		chooseBlueprint:
			overrides.chooseBlueprint ?? (() => Effect.succeed({ status: "cancelled" })),
		chooseProject: overrides.chooseProject ?? (() => Effect.succeed({ status: "cancelled" })),
		readBlueprint: overrides.readBlueprint ?? (() => Effect.succeed(ready())),
		searchBlueprints:
			overrides.searchBlueprints ?? (() => Effect.succeed({ status: "not_configured" }))
	};
}

async function openPath() {
	const user = userEvent.setup();
	await user.type(screen.getByLabelText("Blueprint package path"), assetPath);
	await user.click(screen.getByRole("button", { name: "Open graph" }));
}

describe("BlueprintGraphViewer", () => {
	it("searches the selected project's saved package index and opens a result", async () => {
		const readBlueprint = vi.fn((_path: string) => Effect.succeed(ready()));
		const searchBlueprints = vi.fn((request: { readonly query: string }) => {
			const assets = request.query.toLowerCase().includes("settings")
				? [indexedSettings]
				: [indexedPlayer, indexedSettings];
			return Effect.succeed({
				assets,
				matchCount: assets.length,
				projectName: "ExampleProject",
				status: "ready" as const
			});
		});
		renderViewer(clientWith({ readBlueprint, searchBlueprints }));

		expect(
			await screen.findByRole("button", {
				name: "Open WBP_Settings from project index"
			})
		).toBeDefined();
		const user = userEvent.setup();
		await user.type(screen.getByLabelText("Search indexed Blueprints"), "settings");
		await waitFor(() =>
			expect(searchBlueprints).toHaveBeenLastCalledWith({ query: "settings" })
		);
		expect(
			screen.queryByRole("button", {
				name: "Open BP_PlayerCharacter from project index"
			})
		).toBeNull();

		await user.keyboard("{Enter}");
		await waitFor(() => expect(readBlueprint).toHaveBeenCalledWith(assetPath));
		expect(await screen.findByText("Complete saved-graph projection")).toBeDefined();
		expect(screen.getByLabelText<HTMLInputElement>("Blueprint package path").value).toBe(
			assetPath
		);
	});

	it("offers project selection when indexed search is not configured", async () => {
		let searchCount = 0;
		const chooseProject = vi.fn(() =>
			Effect.succeed({
				project: {
					inputAtlas: "deferred" as const,
					mapCount: 0,
					packageCount: 1,
					projectName: "ExampleProject",
					projectRoot: "C:/Project"
				},
				status: "ready" as const
			})
		);
		renderViewer(
			clientWith({
				chooseProject,
				searchBlueprints: () => {
					searchCount += 1;
					return Effect.succeed(
						searchCount === 1
							? ({ status: "not_configured" } as const)
							: ({
									assets: [indexedSettings],
									matchCount: 1,
									projectName: "ExampleProject",
									status: "ready"
								} as const)
					);
				}
			})
		);

		expect(await screen.findByText("No Workbench project is selected")).toBeDefined();
		await userEvent.setup().click(screen.getByRole("button", { name: "Choose project" }));
		await waitFor(() => expect(chooseProject).toHaveBeenCalledOnce());
		expect(
			await screen.findByRole("button", {
				name: "Open WBP_Settings from project index"
			})
		).toBeDefined();
	});

	it("opens an absolute path and exposes saved topology, pin types, and defaults", async () => {
		const readBlueprint = vi.fn((_path: string) => Effect.succeed(ready()));
		const view = renderViewer(clientWith({ readBlueprint }));

		await openPath();

		await waitFor(() => expect(readBlueprint).toHaveBeenCalledWith(assetPath));
		expect(await screen.findByText("Complete saved-graph projection")).toBeDefined();
		expect(screen.getByText("Topology complete")).toBeDefined();
		expect(screen.getByRole("button", { name: "Inspect On Clicked" })).toBeDefined();
		expect(view.container.querySelectorAll("svg path")).toHaveLength(1);

		await userEvent.setup().click(
			screen.getByRole("button", {
				name: "Inspect Apply Settings With A Deliberately Long Saved Node Name"
			})
		);
		const pins = screen.getByLabelText("Saved pin evidence");
		expect(within(pins).getByText("bool")).toBeDefined();
		expect(within(pins).getByText("Saved default")).toBeDefined();
		expect(within(pins).getByText("true")).toBeDefined();
		expect(within(pins).getByText("Whether the setting is enabled.")).toBeDefined();
	});

	it("shows native partial evidence even when topology coverage has no gaps", async () => {
		renderViewer(
			clientWith({
				readBlueprint: (assetPath) =>
					Effect.succeed({
						assetPath,
						blueprint,
						diagnostics: [
							{
								code: "unsupported_format",
								message: "One node payload remains only partially decoded.",
								severity: "warning" as const
							}
						],
						outcome: "partial" as const,
						status: "ready" as const
					})
			})
		);

		await userEvent
			.setup()
			.type(screen.getByLabelText("Blueprint package path"), "C:/Project/BP_Partial.uasset");
		await userEvent.setup().click(screen.getByRole("button", { name: "Open graph" }));

		expect(await screen.findByText("Topology complete; projection partial")).toBeDefined();
		expect(screen.getByText("Topology complete")).toBeDefined();
		expect(screen.getByText("Partial Blueprint decode")).toBeDefined();
		expect(screen.getByText("One node payload remains only partially decoded.")).toBeDefined();
	});

	it("opens the native picker result, switches graphs, and changes zoom", async () => {
		renderViewer(
			clientWith({
				chooseBlueprint: () => Effect.succeed(ready())
			})
		);
		const user = userEvent.setup();

		await user.click(screen.getByRole("button", { name: "Browse…" }));
		expect(await screen.findByText("Complete saved-graph projection")).toBeDefined();
		expect(screen.getByLabelText<HTMLInputElement>("Blueprint package path").value).toBe(
			assetPath
		);

		await user.click(
			screen.getByRole("button", {
				name: "A Utility Graph With A Very Long Saved Name, 1 nodes"
			})
		);
		expect(screen.getByRole("button", { name: "Inspect Saved Value" })).toBeDefined();
		expect(screen.getByLabelText("Graph zoom").textContent).toBe("100%");
		await user.click(screen.getByRole("button", { name: "Zoom in" }));
		expect(screen.getByLabelText("Graph zoom").textContent).toBe("110%");
		await user.click(screen.getByRole("button", { name: "Zoom out" }));
		expect(screen.getByLabelText("Graph zoom").textContent).toBe("100%");
	});

	it("reports loading and a cancelled picker without treating cancellation as failure", async () => {
		renderViewer(
			clientWith({
				chooseBlueprint: () => Effect.succeed({ status: "cancelled" }),
				readBlueprint: () => Effect.never
			})
		);
		const user = userEvent.setup();
		await user.type(screen.getByLabelText("Blueprint package path"), assetPath);
		await user.click(screen.getByRole("button", { name: "Open graph" }));
		expect(await screen.findByText("Reading saved package")).toBeDefined();
		expect(screen.getByRole("button", { name: "Browse…" }).hasAttribute("disabled")).toBe(true);

		cleanup();
		renderViewer(clientWith());
		await userEvent.setup().click(screen.getByRole("button", { name: "Browse…" }));
		expect(await screen.findByText(/File selection cancelled/)).toBeDefined();
		expect(screen.queryByRole("alert")).toBeNull();
	});

	it("treats a graphless Blueprint as valid saved-package evidence", async () => {
		renderViewer(
			clientWith({
				readBlueprint: () => Effect.succeed(ready({ ...blueprint, graphs: [] }))
			})
		);
		await openPath();

		expect(
			await screen.findByRole("heading", { name: "No saved editor graphs" })
		).toBeDefined();
		expect(screen.getByText(/valid graphless result/)).toBeDefined();
		expect(within(screen.getByLabelText("Blueprint summary")).getAllByText("0")).toHaveLength(
			4
		);
	});

	it("distinguishes metadata-only gaps from incomplete topology", async () => {
		const metadataGap: BlueprintGraphCoverageGap = {
			object_path: callPath,
			reason: "native_node_subclass_tail",
			detail: "24 native subclass bytes remain opaque"
		};
		renderViewer(
			clientWith({
				readBlueprint: () =>
					Effect.succeed(ready({ ...blueprint, coverage_gaps: [metadataGap] }))
			})
		);
		await openPath();

		expect(
			await screen.findByText("Topology complete; specialized metadata partial")
		).toBeDefined();
		expect(screen.getByText(/does not mean graph links are missing/)).toBeDefined();
		await userEvent.setup().click(screen.getByText("1 coverage gaps"));
		expect(screen.getByText("24 native subclass bytes remain opaque")).toBeDefined();
	});

	it("labels unresolved saved references as partial topology", async () => {
		const topologyGap: BlueprintGraphCoverageGap = {
			object_path: eventPath,
			reason: "unresolved_linked_pin",
			detail: "Linked pin owner was not decoded"
		};
		renderViewer(
			clientWith({
				readBlueprint: () =>
					Effect.succeed(ready({ ...blueprint, coverage_gaps: [topologyGap] }))
			})
		);
		await openPath();

		expect(await screen.findByText("Partial saved-graph projection")).toBeDefined();
		expect(screen.getByText("Topology partial")).toBeDefined();
		expect(screen.getByText(/topology may be incomplete/)).toBeDefined();
	});

	it("keeps a dense, widely positioned graph inspectable", async () => {
		const denseNodes = Array.from({ length: 24 }, (_, index) =>
			node({
				classPath: "/Script/BlueprintGraph.K2Node_CallFunction",
				kind: "function_call",
				objectPath: `/Game/UI/BP_Dense.BP_Dense:EventGraph.Node_${index}`,
				pins: [
					pin({ direction: "input", id: `in-${index}`, name: "execute" }),
					pin({ direction: "output", id: `out-${index}`, name: "then" })
				],
				title:
					index === 23
						? "Final Dense Node With A Deliberately Long Saved Evidence Name"
						: `Dense Node ${index}`,
				x: (index % 6) * 520 - 900,
				y: Math.floor(index / 6) * 380 - 600
			})
		);
		const denseLinks = denseNodes.flatMap((source, index) => {
			const target = denseNodes[index + 1];
			return target === undefined
				? []
				: [
						{
							from: { node_object_path: source.object_path, pin_id: `out-${index}` },
							to: {
								node_object_path: target.object_path,
								pin_id: `in-${index + 1}`
							}
						}
					];
		});
		const view = renderViewer(
			clientWith({
				readBlueprint: () =>
					Effect.succeed(
						ready({
							...blueprint,
							graphs: [
								{
									links: denseLinks,
									name: "Dense Event Graph",
									nodes: denseNodes,
									object_path: "/Game/UI/BP_Dense.BP_Dense:EventGraph"
								}
							]
						})
					)
			})
		);
		await openPath();

		expect(view.container.querySelectorAll("svg path")).toHaveLength(23);
		expect(within(screen.getByLabelText("Blueprint summary")).getByText("24")).toBeDefined();
		await userEvent.setup().click(
			screen.getByRole("button", {
				name: "Inspect Final Dense Node With A Deliberately Long Saved Evidence Name"
			})
		);
		expect(
			screen.getByRole("heading", {
				name: "Final Dense Node With A Deliberately Long Saved Evidence Name"
			})
		).toBeDefined();
		await userEvent.setup().click(screen.getByRole("button", { name: "Zoom in" }));
		expect(screen.getByLabelText("Graph zoom").textContent).toBe("110%");
	});

	it.each<readonly [BlueprintGraphFailureReason, string]>([
		["unsupported_version", "This saved package revision is unsupported"],
		["control_rig", "Control Rig uses a different graph model"],
		["malformed_package", "The saved package is malformed"],
		["missing_reader", "The local UAsset reader is unavailable"]
	])("renders the %s recovery state", async (reason, title) => {
		renderViewer(
			clientWith({
				readBlueprint: () =>
					Effect.succeed({
						assetPath,
						message: `Reader reported ${reason}.`,
						reason,
						recovery: "Use the safe recovery for this state.",
						status: "failed"
					})
			})
		);
		await openPath();

		const alert = await screen.findByRole("alert");
		expect(alert.textContent).toContain(title);
		expect(alert.textContent).toContain("Use the safe recovery");
	});

	it("keeps renderer transport failures distinct from package failures", async () => {
		renderViewer(
			clientWith({
				readBlueprint: () =>
					Effect.fail(
						new WorkbenchRendererError({
							cause: "IPC unavailable",
							operation: "blueprintGraphs.read",
							recovery: "Retry"
						})
					)
			})
		);
		await openPath();

		const alert = await screen.findByRole("alert");
		expect(alert.textContent).toContain("local reader request failed");
		expect(alert.textContent).toContain("Unreal is not required");
	});
});
