//! Compact, evaluator-independent projection of saved Blueprint editor graphs.
//!
//! The projection joins `UEdGraph::Nodes` with the native `UEdGraphNode` pin stream. It is enough
//! to lay out and inspect the saved graph, but deliberately does not claim Blueprint compilation
//! or execution semantics.

use std::collections::{HashMap, HashSet};

use serde::{Deserialize, Serialize};
use uasset_parser::asset::{
    DecodedAsset, DecodedBlueprintGraphNode, DecodedUObject, ED_GRAPH_CLASS,
    EdGraphMemberReference, EdGraphPin, EdGraphPinContainerType, EdGraphPinDirection,
    EdGraphPinReference, EdGraphPinType, EdGraphTerminalType,
};
use uasset_parser::package::{Package, PackageIndex};
use uasset_parser::property::{PropertyStream, PropertyValue, RawReason, TextHistory, TextValue};

use crate::generic::{PropertyOutput, property_outputs};

pub const BLUEPRINT_GRAPH_SCHEMA_VERSION: u8 = 1;
const CONTROL_RIG_BLUEPRINT_CLASS: &str = "/Script/ControlRigDeveloper.ControlRigBlueprint";

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct BlueprintGraphProjection {
    pub schema_version: u8,
    pub object_path: String,
    pub graphs: Vec<BlueprintGraph>,
    pub coverage_gaps: Vec<BlueprintGraphCoverageGap>,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct BlueprintGraph {
    pub object_path: String,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub guid: Option<String>,
    pub nodes: Vec<BlueprintNode>,
    pub links: Vec<BlueprintLink>,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct BlueprintNode {
    pub object_path: String,
    pub class_path: String,
    pub kind: BlueprintNodeKind,
    pub title: String,
    pub position: BlueprintNodePosition,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub guid: Option<String>,
    pub properties: Vec<PropertyOutput>,
    pub pins: Vec<BlueprintPin>,
    pub subclass_tail_bytes: u64,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum BlueprintNodeKind {
    Event,
    FunctionCall,
    VariableGet,
    VariableSet,
    Other,
}

#[derive(Clone, Copy, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct BlueprintNodePosition {
    pub x: i64,
    pub y: i64,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
pub struct BlueprintPin {
    pub id: String,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub friendly_name: Option<BlueprintText>,
    pub source_index: i32,
    pub tooltip: String,
    pub direction: BlueprintPinDirection,
    pub pin_type: BlueprintPinType,
    pub default_value: String,
    pub autogenerated_default_value: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_object: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_text_value: Option<BlueprintText>,
    pub linked_to: Vec<BlueprintPinReference>,
    pub sub_pins: Vec<BlueprintPinReference>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_pin: Option<BlueprintPinReference>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reference_pass_through_connection: Option<BlueprintPinReference>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub persistent_guid: Option<String>,
    pub flags: u32,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum BlueprintPinDirection {
    Input,
    Output,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct BlueprintPinType {
    pub category: String,
    pub subcategory: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subcategory_object: Option<String>,
    pub container_type: BlueprintPinContainerType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value_type: Option<BlueprintTerminalType>,
    pub is_reference: bool,
    pub is_weak_pointer: bool,
    pub member_reference: BlueprintMemberReference,
    pub is_const: bool,
    pub is_uobject_wrapper: bool,
    pub serialize_as_single_precision_float: bool,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum BlueprintPinContainerType {
    None,
    Array,
    Set,
    Map,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct BlueprintTerminalType {
    pub category: String,
    pub subcategory: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subcategory_object: Option<String>,
    pub is_const: bool,
    pub is_weak_pointer: bool,
    pub is_uobject_wrapper: bool,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct BlueprintMemberReference {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub guid: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub struct BlueprintPinReference {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub node_object_path: Option<String>,
    pub pin_id: String,
}

#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub struct BlueprintLink {
    pub from: BlueprintPinReference,
    pub to: BlueprintPinReference,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct BlueprintText {
    pub source: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct BlueprintGraphCoverageGap {
    pub object_path: String,
    pub reason: BlueprintGraphCoverageGapReason,
    pub detail: String,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum BlueprintGraphCoverageGapReason {
    MissingNodeReference,
    NullNodeReference,
    NullPin,
    UnresolvedPinOwner,
    UnresolvedLinkedPin,
    UndecodedNodeProperty,
    NativeNodeSubclassTail,
}

/// Projects all saved `UEdGraph` exports in one package.
///
/// A graphless Blueprint produces an empty projection rather than an unsupported failure. The
/// result is absent for non-Blueprint packages and Control Rig Blueprints, whose RigVM model is a
/// separate serialization surface. Graph membership comes from the graph's saved `Nodes` property;
/// link endpoints are normalized and deduplicated so consumers do not have to reconcile the
/// reciprocal links stored on each pin.
#[must_use]
pub fn project_blueprint_graphs(
    package: &Package,
    assets: &[DecodedAsset],
) -> Option<BlueprintGraphProjection> {
    if is_control_rig_blueprint_package(package) {
        return None;
    }
    let blueprint_object_path = blueprint_object_path(package);
    let graph_objects = blueprint_graph_objects(package, assets, blueprint_object_path.as_deref());
    let object_path = blueprint_object_path.or_else(|| {
        graph_objects
            .first()
            .map(|graph| blueprint_path(graph.object_path.as_str()))
    })?;
    let nodes_by_path: HashMap<_, _> = blueprint_nodes(assets)
        .map(|node| (node.object_path.as_str(), node))
        .collect();
    let mut coverage_gaps = Vec::new();
    let graphs = graph_objects
        .into_iter()
        .map(|graph| project_graph(package, graph, &nodes_by_path, &mut coverage_gaps))
        .collect();

    Some(BlueprintGraphProjection {
        schema_version: BLUEPRINT_GRAPH_SCHEMA_VERSION,
        object_path,
        graphs,
        coverage_gaps,
    })
}

/// Returns the object paths referenced by every saved `Nodes` array in a Blueprint package.
///
/// Callers use this membership evidence to decode arbitrary `UEdGraphNode` subclasses without a
/// brittle engine/plugin/project class-name allowlist.
#[must_use]
pub fn saved_blueprint_graph_node_paths(package: &Package, assets: &[DecodedAsset]) -> Vec<String> {
    if is_control_rig_blueprint_package(package) {
        return Vec::new();
    }
    let root = blueprint_object_path(package);
    let mut paths: Vec<_> = blueprint_graph_objects(package, assets, root.as_deref())
        .into_iter()
        .flat_map(|graph| node_references(package, &graph.properties))
        .filter_map(|index| resolve_object(package, index))
        .collect::<HashSet<_>>()
        .into_iter()
        .collect();
    paths.sort();
    paths
}

/// Returns whether a package's Blueprint root uses Control Rig's separate RigVM graph model.
#[must_use]
pub fn is_control_rig_blueprint_package(package: &Package) -> bool {
    package.exports.iter().any(|export| {
        export
            .class_path
            .as_ref()
            .is_some_and(|class_path| class_path.as_str() == CONTROL_RIG_BLUEPRINT_CLASS)
    })
}

fn blueprint_object_path(package: &Package) -> Option<String> {
    package.exports.iter().find_map(|export| {
        export
            .class_path
            .as_ref()
            .is_some_and(|class_path| is_blueprint_asset_class(class_path.as_str()))
            .then(|| export.object_path.to_string())
    })
}

fn blueprint_graph_objects<'a>(
    package: &Package,
    assets: &'a [DecodedAsset],
    blueprint_object_path: Option<&str>,
) -> Vec<&'a DecodedUObject> {
    let graph_prefix = blueprint_object_path.map(|path| format!("{path}."));
    objects(assets)
        .filter(|object| {
            object.class_path.as_str() == ED_GRAPH_CLASS
                || graph_prefix.as_deref().is_some_and(|prefix| {
                    object.object_path.as_str().starts_with(prefix)
                        && matches!(
                            property(package, &object.properties, "Nodes"),
                            Some(PropertyValue::Array(_))
                        )
                })
        })
        .collect()
}

fn is_blueprint_asset_class(class_path: &str) -> bool {
    class_path
        .rsplit('.')
        .next()
        .is_some_and(|class_name| class_name.ends_with("Blueprint"))
}

fn project_graph(
    package: &Package,
    graph: &DecodedUObject,
    nodes_by_path: &HashMap<&str, &DecodedBlueprintGraphNode>,
    coverage_gaps: &mut Vec<BlueprintGraphCoverageGap>,
) -> BlueprintGraph {
    let mut graph_nodes = Vec::new();
    let mut seen_nodes = HashSet::new();
    for node_index in node_references(package, &graph.properties) {
        let Some(node_path) = resolve_object(package, node_index) else {
            coverage_gap(
                coverage_gaps,
                graph.object_path.as_str(),
                BlueprintGraphCoverageGapReason::NullNodeReference,
                "graph Nodes contains a null or unresolved object reference",
            );
            continue;
        };
        let Some(node) = nodes_by_path.get(node_path.as_str()).copied() else {
            coverage_gap(
                coverage_gaps,
                &node_path,
                BlueprintGraphCoverageGapReason::MissingNodeReference,
                "graph node export did not decode as a UE 5.7 Blueprint graph node",
            );
            continue;
        };
        if seen_nodes.insert(node.object_path.as_str()) {
            graph_nodes.push(node);
        }
    }

    // Retain useful topology when a producer omitted or changed the Nodes property, while making
    // the structural inference narrow: only decoded nodes directly beneath this graph qualify.
    if graph_nodes.is_empty() {
        let prefix = format!("{}.", graph.object_path);
        graph_nodes.extend(
            nodes_by_path
                .values()
                .copied()
                .filter(|node| direct_child_of(node.object_path.as_str(), &prefix)),
        );
        graph_nodes.sort_by_key(|node| node.object_path.as_str());
    }

    let directions = pin_directions(&graph_nodes);
    let mut link_set = HashSet::new();
    let mut nodes = Vec::with_capacity(graph_nodes.len());
    for node in graph_nodes {
        for property in &node.properties.records {
            if contains_unprojected_rich_curve_key(&property.value) {
                let property_name = package
                    .resolve_name(property.name)
                    .unwrap_or_else(|| "<unresolved>".to_owned());
                coverage_gap(
                    coverage_gaps,
                    node.object_path.as_str(),
                    BlueprintGraphCoverageGapReason::UndecodedNodeProperty,
                    format!(
                        "property {property_name} contains native FRichCurveKey fields that are preserved but not projected"
                    ),
                );
            }
        }
        if !node.tail.is_empty() {
            coverage_gap(
                coverage_gaps,
                node.object_path.as_str(),
                BlueprintGraphCoverageGapReason::NativeNodeSubclassTail,
                format!(
                    "{} native subclass bytes remain preserved but undecoded",
                    node.tail.len()
                ),
            );
        }

        let pins = node
            .pins
            .iter()
            .enumerate()
            .filter_map(|(index, pin)| {
                let Some(pin) = pin else {
                    coverage_gap(
                        coverage_gaps,
                        node.object_path.as_str(),
                        BlueprintGraphCoverageGapReason::NullPin,
                        format!("serialized pin slot {index} is null"),
                    );
                    return None;
                };
                let own_reference = BlueprintPinReference {
                    node_object_path: Some(node.object_path.to_string()),
                    pin_id: pin.id.to_string(),
                };
                for target in pin.linked_to.iter().flatten() {
                    let target_reference = pin_reference(package, target);
                    if target_reference.node_object_path.is_none() {
                        coverage_gap(
                            coverage_gaps,
                            node.object_path.as_str(),
                            BlueprintGraphCoverageGapReason::UnresolvedPinOwner,
                            format!("pin {} has an unresolved linked-node owner", pin.id),
                        );
                    } else if !directions.contains_key(&target_reference) {
                        coverage_gap(
                            coverage_gaps,
                            target_reference
                                .node_object_path
                                .as_deref()
                                .unwrap_or(node.object_path.as_str()),
                            BlueprintGraphCoverageGapReason::UnresolvedLinkedPin,
                            format!("linked pin {} is not present in this graph", target.pin_id),
                        );
                    }
                    link_set.insert(normalize_link(
                        own_reference.clone(),
                        target_reference,
                        &directions,
                    ));
                }
                Some(project_pin(package, pin))
            })
            .collect();

        nodes.push(BlueprintNode {
            object_path: node.object_path.to_string(),
            class_path: node.class_path.to_string(),
            kind: node_kind(node.class_path.as_str()),
            title: node_title(package, node),
            position: BlueprintNodePosition {
                x: integer_property(package, &node.properties, "NodePosX").unwrap_or(0),
                y: integer_property(package, &node.properties, "NodePosY").unwrap_or(0),
            },
            guid: guid_property(package, &node.properties, "NodeGuid"),
            properties: property_outputs(package, node.properties.clone()),
            pins,
            subclass_tail_bytes: node.tail.len(),
        });
    }

    let mut links: Vec<_> = link_set.into_iter().collect();
    links.sort();
    BlueprintGraph {
        object_path: graph.object_path.to_string(),
        name: graph
            .object_path
            .as_str()
            .rsplit('.')
            .next()
            .unwrap_or(graph.object_path.as_str())
            .to_owned(),
        guid: guid_property(package, &graph.properties, "GraphGuid"),
        nodes,
        links,
    }
}

fn contains_unprojected_rich_curve_key(value: &PropertyValue) -> bool {
    match value {
        PropertyValue::Raw {
            reason: RawReason::DecoderRejected(detail),
        } => detail.contains("FRichCurveKey"),
        PropertyValue::Array(values) | PropertyValue::Set(values) => {
            values.iter().any(contains_unprojected_rich_curve_key)
        }
        PropertyValue::Map(entries) => entries.iter().any(|entry| {
            contains_unprojected_rich_curve_key(&entry.key)
                || contains_unprojected_rich_curve_key(&entry.value)
        }),
        PropertyValue::Struct(stream) => stream
            .records
            .iter()
            .any(|record| contains_unprojected_rich_curve_key(&record.value)),
        _ => false,
    }
}

fn project_pin(package: &Package, pin: &EdGraphPin) -> BlueprintPin {
    BlueprintPin {
        id: pin.id.to_string(),
        name: resolve_name(package, pin.name),
        friendly_name: project_text(&pin.friendly_name),
        source_index: pin.source_index,
        tooltip: pin.tooltip.clone(),
        direction: match pin.direction {
            EdGraphPinDirection::Input => BlueprintPinDirection::Input,
            EdGraphPinDirection::Output => BlueprintPinDirection::Output,
        },
        pin_type: project_pin_type(package, &pin.pin_type),
        default_value: pin.default_value.clone(),
        autogenerated_default_value: pin.autogenerated_default_value.clone(),
        default_object: resolve_object(package, pin.default_object),
        default_text_value: project_text(&pin.default_text_value),
        linked_to: pin
            .linked_to
            .iter()
            .flatten()
            .map(|reference| pin_reference(package, reference))
            .collect(),
        sub_pins: pin
            .sub_pins
            .iter()
            .flatten()
            .map(|reference| pin_reference(package, reference))
            .collect(),
        parent_pin: pin
            .parent_pin
            .as_ref()
            .map(|reference| pin_reference(package, reference)),
        reference_pass_through_connection: pin
            .reference_pass_through_connection
            .as_ref()
            .map(|reference| pin_reference(package, reference)),
        persistent_guid: (!pin.persistent_guid.is_zero()).then(|| pin.persistent_guid.to_string()),
        flags: pin.flags,
    }
}

fn project_pin_type(package: &Package, pin_type: &EdGraphPinType) -> BlueprintPinType {
    BlueprintPinType {
        category: resolve_name(package, pin_type.category),
        subcategory: resolve_name(package, pin_type.subcategory),
        subcategory_object: resolve_object(package, pin_type.subcategory_object),
        container_type: match pin_type.container_type {
            EdGraphPinContainerType::None => BlueprintPinContainerType::None,
            EdGraphPinContainerType::Array => BlueprintPinContainerType::Array,
            EdGraphPinContainerType::Set => BlueprintPinContainerType::Set,
            EdGraphPinContainerType::Map => BlueprintPinContainerType::Map,
        },
        value_type: pin_type
            .value_type
            .as_ref()
            .map(|value| project_terminal_type(package, value)),
        is_reference: pin_type.is_reference,
        is_weak_pointer: pin_type.is_weak_pointer,
        member_reference: project_member_reference(package, &pin_type.member_reference),
        is_const: pin_type.is_const,
        is_uobject_wrapper: pin_type.is_uobject_wrapper,
        serialize_as_single_precision_float: pin_type.serialize_as_single_precision_float,
    }
}

fn project_terminal_type(
    package: &Package,
    terminal: &EdGraphTerminalType,
) -> BlueprintTerminalType {
    BlueprintTerminalType {
        category: resolve_name(package, terminal.category),
        subcategory: resolve_name(package, terminal.subcategory),
        subcategory_object: resolve_object(package, terminal.subcategory_object),
        is_const: terminal.is_const,
        is_weak_pointer: terminal.is_weak_pointer,
        is_uobject_wrapper: terminal.is_uobject_wrapper,
    }
}

fn project_member_reference(
    package: &Package,
    reference: &EdGraphMemberReference,
) -> BlueprintMemberReference {
    BlueprintMemberReference {
        parent: resolve_object(package, reference.parent),
        name: resolve_name(package, reference.name),
        guid: (!reference.guid.is_zero()).then(|| reference.guid.to_string()),
    }
}

fn pin_reference(package: &Package, reference: &EdGraphPinReference) -> BlueprintPinReference {
    BlueprintPinReference {
        node_object_path: resolve_object(package, reference.owning_node),
        pin_id: reference.pin_id.to_string(),
    }
}

fn normalize_link(
    first: BlueprintPinReference,
    second: BlueprintPinReference,
    directions: &HashMap<BlueprintPinReference, BlueprintPinDirection>,
) -> BlueprintLink {
    match (directions.get(&first), directions.get(&second)) {
        (Some(BlueprintPinDirection::Output), Some(BlueprintPinDirection::Input)) => {
            BlueprintLink {
                from: first,
                to: second,
            }
        }
        (Some(BlueprintPinDirection::Input), Some(BlueprintPinDirection::Output)) => {
            BlueprintLink {
                from: second,
                to: first,
            }
        }
        _ if first <= second => BlueprintLink {
            from: first,
            to: second,
        },
        _ => BlueprintLink {
            from: second,
            to: first,
        },
    }
}

fn pin_directions(
    nodes: &[&DecodedBlueprintGraphNode],
) -> HashMap<BlueprintPinReference, BlueprintPinDirection> {
    nodes
        .iter()
        .flat_map(|node| {
            node.pins.iter().flatten().map(|pin| {
                (
                    BlueprintPinReference {
                        node_object_path: Some(node.object_path.to_string()),
                        pin_id: pin.id.to_string(),
                    },
                    match pin.direction {
                        EdGraphPinDirection::Input => BlueprintPinDirection::Input,
                        EdGraphPinDirection::Output => BlueprintPinDirection::Output,
                    },
                )
            })
        })
        .collect()
}

fn node_kind(class_path: &str) -> BlueprintNodeKind {
    match class_path.rsplit('.').next() {
        Some("K2Node_Event" | "K2Node_CustomEvent") => BlueprintNodeKind::Event,
        Some("K2Node_CallFunction") => BlueprintNodeKind::FunctionCall,
        Some("K2Node_VariableGet") => BlueprintNodeKind::VariableGet,
        Some("K2Node_VariableSet") => BlueprintNodeKind::VariableSet,
        _ => BlueprintNodeKind::Other,
    }
}

fn node_title(package: &Package, node: &DecodedBlueprintGraphNode) -> String {
    ["EventReference", "FunctionReference", "VariableReference"]
        .iter()
        .find_map(|property_name| {
            let PropertyValue::Struct(reference) =
                property(package, &node.properties, property_name)?
            else {
                return None;
            };
            let PropertyValue::Name(member_name) = property(package, reference, "MemberName")?
            else {
                return None;
            };
            package.resolve_name(*member_name)
        })
        .or_else(|| {
            node.class_path
                .as_str()
                .rsplit('.')
                .next()
                .map(str::to_owned)
        })
        .unwrap_or_else(|| node.object_path.to_string())
}

fn node_references(package: &Package, properties: &PropertyStream) -> Vec<PackageIndex> {
    let Some(PropertyValue::Array(values)) = property(package, properties, "Nodes") else {
        return Vec::new();
    };
    values
        .iter()
        .filter_map(|value| match value {
            PropertyValue::ObjectRef(index) => Some(*index),
            _ => None,
        })
        .collect()
}

fn property<'a>(
    package: &Package,
    stream: &'a PropertyStream,
    property_name: &str,
) -> Option<&'a PropertyValue> {
    stream.records.iter().find_map(|record| {
        (package.resolve_name_str(record.name) == Some(property_name)).then_some(&record.value)
    })
}

fn integer_property(
    package: &Package,
    properties: &PropertyStream,
    property_name: &str,
) -> Option<i64> {
    match property(package, properties, property_name)? {
        PropertyValue::Int(value) => Some(*value),
        PropertyValue::UInt(value) => i64::try_from(*value).ok(),
        _ => None,
    }
}

fn guid_property(
    package: &Package,
    properties: &PropertyStream,
    property_name: &str,
) -> Option<String> {
    let PropertyValue::Guid(value) = property(package, properties, property_name)? else {
        return None;
    };
    Some(value.to_string())
}

fn project_text(text: &TextValue) -> Option<BlueprintText> {
    if text.source.is_empty() {
        return None;
    }
    let (namespace, key) = match &text.history {
        TextHistory::None => (None, None),
        TextHistory::Base { namespace, key } => (
            Some(namespace.clone()),
            (!key.is_empty()).then(|| key.clone()),
        ),
        TextHistory::NamedFormat { format, .. } => text_identity_parts(format),
    };
    Some(BlueprintText {
        source: text.source.clone(),
        namespace,
        key,
    })
}

fn text_identity_parts(text: &TextValue) -> (Option<String>, Option<String>) {
    match &text.history {
        TextHistory::None => (None, None),
        TextHistory::Base { namespace, key } => (
            Some(namespace.clone()),
            (!key.is_empty()).then(|| key.clone()),
        ),
        TextHistory::NamedFormat { format, .. } => text_identity_parts(format),
    }
}

fn resolve_name(package: &Package, name: uasset_parser::archive::NameRef) -> String {
    package
        .resolve_name_cow(name)
        .map(|name| name.into_owned())
        .unwrap_or_else(|| "<unresolved>".to_owned())
}

fn resolve_object(package: &Package, index: PackageIndex) -> Option<String> {
    (index != PackageIndex::Null)
        .then(|| package.resolve_index_str(index).map(str::to_owned))
        .flatten()
}

fn blueprint_path(graph_path: &str) -> String {
    graph_path
        .rsplit_once('.')
        .map_or_else(|| graph_path.to_owned(), |(parent, _)| parent.to_owned())
}

fn direct_child_of(object_path: &str, graph_prefix: &str) -> bool {
    object_path
        .strip_prefix(graph_prefix)
        .is_some_and(|suffix| !suffix.contains('.'))
}

fn objects(assets: &[DecodedAsset]) -> impl Iterator<Item = &DecodedUObject> {
    assets.iter().filter_map(|asset| match asset {
        DecodedAsset::UObject(object) => Some(object),
        _ => None,
    })
}

fn blueprint_nodes(assets: &[DecodedAsset]) -> impl Iterator<Item = &DecodedBlueprintGraphNode> {
    assets.iter().filter_map(|asset| match asset {
        DecodedAsset::BlueprintGraphNode(node) => Some(node),
        _ => None,
    })
}

fn coverage_gap(
    gaps: &mut Vec<BlueprintGraphCoverageGap>,
    object_path: &str,
    reason: BlueprintGraphCoverageGapReason,
    detail: impl Into<String>,
) {
    gaps.push(BlueprintGraphCoverageGap {
        object_path: object_path.to_owned(),
        reason,
        detail: detail.into(),
    });
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn recognizes_engine_and_custom_blueprint_asset_classes() {
        assert!(is_blueprint_asset_class("/Script/Engine.Blueprint"));
        assert!(is_blueprint_asset_class(
            "/Script/UMGEditor.WidgetBlueprint"
        ));
        assert!(is_blueprint_asset_class(
            "/Script/ProjectEditor.CustomBlueprint"
        ));
        assert!(!is_blueprint_asset_class(
            "/Script/Engine.BlueprintGeneratedClass"
        ));
    }
}
