import { Schema } from "effect";
import { SavedProperty } from "./uasset-inspection.js";

const NonNegativeInt = Schema.Int.check(Schema.isGreaterThanOrEqualTo(0));

export const BlueprintGraphCoverageGap = Schema.Struct({
	object_path: Schema.String,
	reason: Schema.Literals([
		"missing_node_reference",
		"null_node_reference",
		"null_pin",
		"unresolved_pin_owner",
		"unresolved_linked_pin",
		"undecoded_node_property",
		"native_node_subclass_tail"
	]),
	detail: Schema.String
}).annotate({ identifier: "BlueprintGraphCoverageGap" });
export interface BlueprintGraphCoverageGap extends Schema.Schema.Type<
	typeof BlueprintGraphCoverageGap
> {}

export const BlueprintPinReference = Schema.Struct({
	node_object_path: Schema.optionalKey(Schema.String),
	pin_id: Schema.String
}).annotate({ identifier: "BlueprintPinReference" });
export interface BlueprintPinReference extends Schema.Schema.Type<typeof BlueprintPinReference> {}

export const BlueprintText = Schema.Struct({
	source: Schema.String,
	namespace: Schema.optionalKey(Schema.String),
	key: Schema.optionalKey(Schema.String)
}).annotate({ identifier: "BlueprintText" });
export interface BlueprintText extends Schema.Schema.Type<typeof BlueprintText> {}

export const BlueprintMemberReference = Schema.Struct({
	parent: Schema.optionalKey(Schema.String),
	name: Schema.String,
	guid: Schema.optionalKey(Schema.String)
}).annotate({ identifier: "BlueprintMemberReference" });
export interface BlueprintMemberReference extends Schema.Schema.Type<
	typeof BlueprintMemberReference
> {}

export const BlueprintTerminalType = Schema.Struct({
	category: Schema.String,
	subcategory: Schema.String,
	subcategory_object: Schema.optionalKey(Schema.String),
	is_const: Schema.Boolean,
	is_weak_pointer: Schema.Boolean,
	is_uobject_wrapper: Schema.Boolean
}).annotate({ identifier: "BlueprintTerminalType" });
export interface BlueprintTerminalType extends Schema.Schema.Type<typeof BlueprintTerminalType> {}

export const BlueprintPinType = Schema.Struct({
	category: Schema.String,
	subcategory: Schema.String,
	subcategory_object: Schema.optionalKey(Schema.String),
	container_type: Schema.Literals(["none", "array", "set", "map"]),
	value_type: Schema.optionalKey(BlueprintTerminalType),
	is_reference: Schema.Boolean,
	is_weak_pointer: Schema.Boolean,
	member_reference: BlueprintMemberReference,
	is_const: Schema.Boolean,
	is_uobject_wrapper: Schema.Boolean,
	serialize_as_single_precision_float: Schema.Boolean
}).annotate({ identifier: "BlueprintPinType" });
export interface BlueprintPinType extends Schema.Schema.Type<typeof BlueprintPinType> {}

export const BlueprintPin = Schema.Struct({
	id: Schema.String,
	name: Schema.String,
	friendly_name: Schema.optionalKey(BlueprintText),
	source_index: Schema.Int,
	tooltip: Schema.String,
	direction: Schema.Literals(["input", "output"]),
	pin_type: BlueprintPinType,
	default_value: Schema.String,
	autogenerated_default_value: Schema.String,
	default_object: Schema.optionalKey(Schema.String),
	default_text_value: Schema.optionalKey(BlueprintText),
	linked_to: Schema.Array(BlueprintPinReference),
	sub_pins: Schema.Array(BlueprintPinReference),
	parent_pin: Schema.optionalKey(BlueprintPinReference),
	reference_pass_through_connection: Schema.optionalKey(BlueprintPinReference),
	persistent_guid: Schema.optionalKey(Schema.String),
	flags: NonNegativeInt
}).annotate({ identifier: "BlueprintPin" });
export interface BlueprintPin extends Schema.Schema.Type<typeof BlueprintPin> {}

export const BlueprintNode = Schema.Struct({
	object_path: Schema.String,
	class_path: Schema.String,
	kind: Schema.Literals(["event", "function_call", "variable_get", "variable_set", "other"]),
	title: Schema.String,
	position: Schema.Struct({ x: Schema.Int, y: Schema.Int }),
	guid: Schema.optionalKey(Schema.String),
	properties: Schema.Array(SavedProperty),
	pins: Schema.Array(BlueprintPin),
	subclass_tail_bytes: NonNegativeInt
}).annotate({ identifier: "BlueprintNode" });
export interface BlueprintNode extends Schema.Schema.Type<typeof BlueprintNode> {}

export const BlueprintLink = Schema.Struct({
	from: BlueprintPinReference,
	to: BlueprintPinReference
}).annotate({ identifier: "BlueprintLink" });
export interface BlueprintLink extends Schema.Schema.Type<typeof BlueprintLink> {}

export const BlueprintGraph = Schema.Struct({
	object_path: Schema.String,
	name: Schema.String,
	guid: Schema.optionalKey(Schema.String),
	nodes: Schema.Array(BlueprintNode),
	links: Schema.Array(BlueprintLink)
}).annotate({ identifier: "BlueprintGraph" });
export interface BlueprintGraph extends Schema.Schema.Type<typeof BlueprintGraph> {}

export const BlueprintGraphProjection = Schema.Struct({
	schema_version: Schema.Literal(1),
	object_path: Schema.String,
	graphs: Schema.Array(BlueprintGraph),
	coverage_gaps: Schema.Array(BlueprintGraphCoverageGap)
}).annotate({ identifier: "BlueprintGraphProjection" });
export interface BlueprintGraphProjection extends Schema.Schema.Type<
	typeof BlueprintGraphProjection
> {}

export const decodeBlueprintGraphProjection = Schema.decodeUnknownEffect(BlueprintGraphProjection);
