import { createReadStream } from "node:fs";
import { mkdir, open, readFile, stat } from "node:fs/promises";
import { get as httpGet, type IncomingMessage } from "node:http";
import { get as httpsGet } from "node:https";
import { basename, dirname, join, resolve } from "node:path";
import { URL } from "node:url";
import { Context, Effect, Layer, Schema } from "effect";
import {
	PluginInstallCancelled,
	PluginDistributionValidationError,
	ReleaseUnavailable,
	TransportFailure
} from "./errors.js";
import type { PluginBundleManifest } from "./manifest.js";
import type {
	PluginInstallProgress,
	PluginDistributionLimits,
	PluginSourceProvenance
} from "./model.js";

const COPY_CHUNK_BYTES = 64 * 1024;

export interface PluginReleaseDocument {
	readonly bytes: Uint8Array;
	readonly manifest: Schema.Json;
	readonly provenance: PluginSourceProvenance;
}

export interface PluginReleaseSourceApi {
	readonly fetchArtifact: (options: {
		readonly destination: string;
		readonly limits: PluginDistributionLimits;
		readonly manifest: PluginBundleManifest;
		readonly onProgress?: (progress: PluginInstallProgress) => void;
	}) => Effect.Effect<
		PluginSourceProvenance,
		ReleaseUnavailable | TransportFailure | PluginInstallCancelled
	>;
	readonly fetchManifest: (options: {
		readonly limits: PluginDistributionLimits;
		readonly releaseVersion: string;
	}) => Effect.Effect<
		PluginReleaseDocument,
		ReleaseUnavailable | TransportFailure | PluginInstallCancelled
	>;
	readonly sourceId: string;
}

export class PluginReleaseSource extends Context.Service<
	PluginReleaseSource,
	PluginReleaseSourceApi
>()("@ue-shed/plugin-distribution/PluginReleaseSource") {}

function cancelled(releaseVersion: string, stage: string) {
	return new PluginInstallCancelled({
		message: `Plugin install was cancelled during ${stage}.`,
		recovery: "Retry installing the exact release when the host is ready.",
		releaseVersion,
		retrySafe: true,
		stage
	});
}

function unavailable(releaseVersion: string, message: string) {
	return new ReleaseUnavailable({
		message,
		recovery: "Confirm the exact release exists and the configured source contains its assets.",
		releaseVersion,
		retrySafe: true
	});
}

function transport(releaseVersion: string, operation: string, cause: unknown) {
	return new TransportFailure({
		message: `${operation} failed: ${String(cause)}`,
		operation,
		recovery: "Check source availability and retry the exact immutable release.",
		releaseVersion,
		retrySafe: true
	});
}

function parseJson(bytes: Uint8Array, releaseVersion: string): Schema.Json {
	try {
		return Schema.decodeUnknownSync(Schema.Json)(
			JSON.parse(Buffer.from(bytes).toString("utf8"))
		);
	} catch (cause) {
		throw new PluginDistributionValidationError({
			field: "manifest",
			message: `Release ${releaseVersion} has malformed manifest JSON: ${String(cause)}`,
			recovery: "Use a manifest generated by UE Shed release tooling.",
			retrySafe: false
		});
	}
}

async function readBounded(path: string, maximumBytes: number, signal: AbortSignal) {
	const details = await stat(path);
	if (!details.isFile()) throw new Error(`Path is not a regular file: ${path}`);
	if (details.size > maximumBytes) throw new Error(`File exceeds ${maximumBytes} bytes: ${path}`);
	return readFile(path, { signal });
}

async function copyBounded(options: {
	readonly destination: string;
	readonly maximumBytes: number;
	readonly onChunk: (completed: number, total: number) => void;
	readonly signal: AbortSignal;
	readonly source: string;
}) {
	const details = await stat(options.source);
	if (!details.isFile()) throw new Error(`Artifact is not a regular file: ${options.source}`);
	if (details.size > options.maximumBytes) {
		throw new Error(`Artifact exceeds ${options.maximumBytes} bytes.`);
	}
	await mkdir(dirname(options.destination), { recursive: true });
	const destination = await open(options.destination, "wx");
	let completed = 0;
	try {
		for await (const chunk of createReadStream(options.source, {
			highWaterMark: COPY_CHUNK_BYTES,
			signal: options.signal
		})) {
			if (options.signal.aborted) throw new DOMException("Cancelled", "AbortError");
			await destination.writeFile(chunk, { signal: options.signal });
			completed += chunk.byteLength;
			options.onChunk(completed, details.size);
		}
	} finally {
		await destination.close();
	}
}

export function pluginReleaseAssetNames(releaseVersion: string) {
	return {
		artifact: `ue-shed-plugins-${releaseVersion}.tar.gz`,
		manifest: `ue-shed-plugins-${releaseVersion}.manifest.json`
	} as const;
}

export function mapReviewPluginReleaseAssetNames(releaseVersion: string) {
	return {
		artifact: `ue-shed-plugins-map-review-${releaseVersion}.tar.gz`,
		manifest: `ue-shed-plugins-map-review-${releaseVersion}.manifest.json`
	} as const;
}

export interface LocalPluginReleaseSourceOptions {
	readonly artifactPath?: string;
	readonly directory?: string;
	readonly manifestPath?: string;
	readonly sourceId?: string;
}

export const localPluginReleaseSourceLayer = (
	options: LocalPluginReleaseSourceOptions
): Layer.Layer<PluginReleaseSource> =>
	Layer.succeed(
		PluginReleaseSource,
		PluginReleaseSource.of({
			sourceId: options.sourceId ?? "local-artifact",
			fetchManifest: Effect.fn("PluginReleaseSource.local.fetchManifest")((request) =>
				Effect.tryPromise({
					try: async (signal) => {
						const path = resolve(
							options.manifestPath ??
								join(
									options.directory ?? ".",
									pluginReleaseAssetNames(request.releaseVersion).manifest
								)
						);
						const bytes = await readBounded(
							path,
							request.limits.maximumManifestBytes,
							signal
						);
						return {
							bytes,
							manifest: parseJson(bytes, request.releaseVersion),
							provenance: {
								detail: path,
								kind: "local",
								sourceId: options.sourceId ?? "local-artifact"
							}
						};
					},
					catch: (cause) =>
						cause instanceof PluginDistributionValidationError
							? transport(request.releaseVersion, "Decode local manifest", cause)
							: unavailable(
									request.releaseVersion,
									`Local release manifest is unavailable: ${String(cause)}`
								)
				})
			),
			fetchArtifact: Effect.fn("PluginReleaseSource.local.fetchArtifact")((request) =>
				Effect.tryPromise({
					try: async (signal) => {
						const path = resolve(
							options.artifactPath ??
								join(
									options.directory ?? ".",
									basename(request.manifest.artifact.path)
								)
						);
						await copyBounded({
							destination: request.destination,
							maximumBytes: request.limits.maximumArtifactBytes,
							onChunk: (bytesCompleted, bytesTotal) =>
								request.onProgress?.({
									bytesCompleted,
									bytesTotal,
									phase: "downloading",
									releaseVersion: request.manifest.releaseVersion
								}),
							signal,
							source: path
						});
						return {
							detail: path,
							kind: "local",
							sourceId: options.sourceId ?? "local-artifact"
						};
					},
					catch: (cause) =>
						cause instanceof DOMException && cause.name === "AbortError"
							? cancelled(request.manifest.releaseVersion, "download")
							: unavailable(
									request.manifest.releaseVersion,
									`Local plugin artifact is unavailable: ${String(cause)}`
								)
				})
			)
		})
	);

interface HttpResponse {
	readonly response: IncomingMessage;
	readonly url: URL;
}

function requestUrl(url: URL, signal: AbortSignal): Promise<HttpResponse> {
	return new Promise((resolveResponse, rejectResponse) => {
		const request = (url.protocol === "https:" ? httpsGet : httpGet)(
			url,
			{ headers: { "user-agent": "ue-shed-plugin-distribution" }, signal },
			(response) => resolveResponse({ response, url })
		);
		request.once("error", rejectResponse);
	});
}

async function httpResponse(
	url: URL,
	signal: AbortSignal,
	redirectsRemaining = 5
): Promise<HttpResponse> {
	const result = await requestUrl(url, signal);
	const status = result.response.statusCode ?? 0;
	if (status >= 300 && status < 400 && result.response.headers.location !== undefined) {
		result.response.resume();
		if (redirectsRemaining === 0) throw new Error("HTTP redirect limit exceeded.");
		return httpResponse(
			new URL(result.response.headers.location, url),
			signal,
			redirectsRemaining - 1
		);
	}
	return result;
}

async function readHttpBody(response: IncomingMessage, maximumBytes: number, signal: AbortSignal) {
	const chunks: Buffer[] = [];
	let bytes = 0;
	for await (const chunk of response) {
		if (signal.aborted) throw new DOMException("Cancelled", "AbortError");
		bytes += chunk.byteLength;
		if (bytes > maximumBytes) throw new Error(`HTTP body exceeds ${maximumBytes} bytes.`);
		chunks.push(Buffer.from(chunk));
	}
	return Buffer.concat(chunks);
}

export interface HttpPluginReleaseSourceOptions {
	readonly assetNames?: (releaseVersion: string) => {
		readonly artifact: string;
		readonly manifest: string;
	};
	readonly baseUrl: string;
	readonly kind?: "http" | "github";
	readonly releaseDirectory?: (releaseVersion: string) => string;
	readonly sourceId?: string;
}

export const httpPluginReleaseSourceLayer = (
	options: HttpPluginReleaseSourceOptions
): Layer.Layer<PluginReleaseSource> => {
	const baseUrl = new URL(
		options.baseUrl.endsWith("/") ? options.baseUrl : `${options.baseUrl}/`
	);
	const sourceId = options.sourceId ?? baseUrl.origin;
	const assetUrl = (releaseVersion: string, kind: "artifact" | "manifest") => {
		const names = (options.assetNames ?? pluginReleaseAssetNames)(releaseVersion);
		const directory = options.releaseDirectory?.(releaseVersion) ?? "";
		return new URL(`${directory.length > 0 ? `${directory}/` : ""}${names[kind]}`, baseUrl);
	};
	const provenance = (detail: string): PluginSourceProvenance => ({
		detail,
		kind: options.kind ?? "http",
		sourceId
	});
	return Layer.succeed(
		PluginReleaseSource,
		PluginReleaseSource.of({
			sourceId,
			fetchManifest: Effect.fn("PluginReleaseSource.http.fetchManifest")((request) =>
				Effect.tryPromise({
					try: async (signal) => {
						const url = assetUrl(request.releaseVersion, "manifest");
						const { response } = await httpResponse(url, signal);
						if (response.statusCode !== 200) {
							response.resume();
							throw unavailable(
								request.releaseVersion,
								`Release manifest request returned HTTP ${String(response.statusCode)}.`
							);
						}
						const bytes = await readHttpBody(
							response,
							request.limits.maximumManifestBytes,
							signal
						);
						return {
							bytes,
							manifest: parseJson(bytes, request.releaseVersion),
							provenance: provenance(url.toString())
						};
					},
					catch: (cause) => {
						if (cause instanceof ReleaseUnavailable) return cause;
						if (cause instanceof DOMException && cause.name === "AbortError") {
							return cancelled(request.releaseVersion, "manifest download");
						}
						return transport(
							request.releaseVersion,
							"Download release manifest",
							cause
						);
					}
				})
			),
			fetchArtifact: Effect.fn("PluginReleaseSource.http.fetchArtifact")((request) =>
				Effect.tryPromise({
					try: async (signal) => {
						const url = assetUrl(request.manifest.releaseVersion, "artifact");
						const { response } = await httpResponse(url, signal);
						if (response.statusCode !== 200) {
							response.resume();
							throw unavailable(
								request.manifest.releaseVersion,
								`Plugin artifact request returned HTTP ${String(response.statusCode)}.`
							);
						}
						const declaredLength = Number(response.headers["content-length"] ?? 0);
						if (
							Number.isFinite(declaredLength) &&
							declaredLength > request.limits.maximumArtifactBytes
						) {
							response.destroy();
							throw new Error("HTTP artifact exceeds the configured byte limit.");
						}
						await mkdir(dirname(request.destination), { recursive: true });
						const destination = await open(request.destination, "wx");
						let completed = 0;
						try {
							for await (const chunk of response) {
								if (signal.aborted)
									throw new DOMException("Cancelled", "AbortError");
								completed += chunk.byteLength;
								if (completed > request.limits.maximumArtifactBytes) {
									throw new Error(
										"HTTP artifact exceeds the configured byte limit."
									);
								}
								await destination.write(chunk);
								request.onProgress?.({
									bytesCompleted: completed,
									...(declaredLength > 0
										? { bytesTotal: declaredLength }
										: undefined),
									phase: "downloading",
									releaseVersion: request.manifest.releaseVersion
								});
							}
						} finally {
							await destination.close();
						}
						return provenance(url.toString());
					},
					catch: (cause) => {
						if (cause instanceof ReleaseUnavailable) return cause;
						if (cause instanceof DOMException && cause.name === "AbortError") {
							return cancelled(request.manifest.releaseVersion, "download");
						}
						return transport(
							request.manifest.releaseVersion,
							"Download plugin artifact",
							cause
						);
					}
				})
			)
		})
	);
};

export const githubReleaseSourceLayer = (options: {
	readonly owner: string;
	readonly repository: string;
	readonly sourceId?: string;
}): Layer.Layer<PluginReleaseSource> =>
	httpPluginReleaseSourceLayer({
		assetNames: mapReviewPluginReleaseAssetNames,
		baseUrl: `https://github.com/${encodeURIComponent(options.owner)}/${encodeURIComponent(options.repository)}/releases/download/`,
		kind: "github",
		releaseDirectory: (releaseVersion) => `v${releaseVersion}`,
		sourceId: options.sourceId ?? `${options.owner}/${options.repository}`
	});
