// GENERATED by scripts/site-media.ts — refresh with pnpm site:media.
export const siteMedia = {
	exportedAt: "2026-10-01T03:33:27.762Z",
	captures: {
		authoring: {
			file: "authoring.png",
			journey: "site-saved",
			title: "Inspect a saved DataTable",
			sha256: "6bb39fd1ae6c502510b35c3cdfbdfc97681e8482b99afc61b77cc1526d198e30"
		},
		gameText: {
			file: "game-text.png",
			journey: "site-saved",
			title: "Investigate a shared source line",
			sha256: "1b9c57ab2be91decc6f8ec5a575634d06bcd9efe8a354cdf93d472182489cb92"
		},
		mapReview: {
			file: "map-review.png",
			journey: "site-saved",
			title: "Start review from the saved Camera Lab map",
			sha256: "efdbb19740c51b27b0f7520c60246163a88e420fdc7fe079752c2604fdbd847d"
		},
		authoringCharts: {
			file: "authoring-charts.png",
			journey: "site-saved",
			title: "Chart the open DataTable",
			sha256: "481d2633a82cb70c9ff674d4a2b5eb36bedcce588bff23b77567275207573b1d"
		},
		configExplorer: {
			file: "config-explorer.png",
			journey: "site-saved",
			title: "Compare saved config across platforms",
			sha256: "3bea96cd819044b28c88670b2f6df225f7953959b106c8b1c5af111170a83b15"
		},
		configLineage: {
			file: "config-lineage.png",
			journey: "site-saved",
			title: "Trace the winning value",
			sha256: "47e8c5508809392a8780b0f29254909299ce45d3ca2fb2801d6e90d58cbb1ea4"
		}
	},
	journeys: {
		"site-saved": {
			recordingId: "20261001033247344-site-saved-dbe5c70a",
			commit: "8de10909",
			dirty: true,
			finishedAt: "2026-10-01T03:33:26.701Z"
		}
	}
} as const;
