// GENERATED by scripts/site-media.ts — refresh with pnpm site:media.
export const siteMedia = {
	exportedAt: "2026-09-30T21:43:42.734Z",
	captures: {
		authoring: {
			file: "authoring.png",
			journey: "site-saved",
			title: "Inspect a saved DataTable",
			sha256: "158ab3ea648966817c467a336050776f7c61f78423a9839c13dcb0c7d3625a9e"
		},
		gameText: {
			file: "game-text.png",
			journey: "site-saved",
			title: "Investigate a shared source line",
			sha256: "1b9c57ab2be91decc6f8ec5a575634d06bcd9efe8a354cdf93d472182489cb92"
		},
		mapReview: {
			file: "map-review.png",
			journey: "map-review",
			title: "Review the colorful Camera Lab map",
			sha256: "a92aba65166095925c5132835a07c3258c552db06dfd5ecd5892934c35662ec5"
		},
		authoringCharts: {
			file: "authoring-charts.png",
			journey: "site-saved",
			title: "Chart the open DataTable",
			sha256: "481d2633a82cb70c9ff674d4a2b5eb36bedcce588bff23b77567275207573b1d"
		},
		configExplorer: {
			file: "config-explorer.png",
			journey: "site-saved",
			title: "Compare saved config across platforms",
			sha256: "3bea96cd819044b28c88670b2f6df225f7953959b106c8b1c5af111170a83b15"
		},
		configLineage: {
			file: "config-lineage.png",
			journey: "site-saved",
			title: "Trace the winning value",
			sha256: "47e8c5508809392a8780b0f29254909299ce45d3ca2fb2801d6e90d58cbb1ea4"
		}
	},
	journeys: {
		"map-review": {
			recordingId: "20260927185707853-map-review-2ca25292",
			commit: "f27a5b4f",
			dirty: true,
			finishedAt: "2026-09-27T18:57:26.519Z"
		},
		"site-saved": {
			recordingId: "20260930214256491-site-saved-ecd18abf",
			commit: "4191d856",
			dirty: true,
			finishedAt: "2026-09-30T21:43:41.746Z"
		}
	}
} as const;
