// GENERATED by scripts/site-media.ts — refresh with pnpm site:media.
export const siteMedia = {
	exportedAt: "2026-09-27T18:58:42.215Z",
	captures: {
		authoring: {
			file: "authoring.png",
			journey: "site-saved",
			title: "Inspect a saved DataTable",
			sha256: "a7bab7ced7356cff266551ced77d9040929b8a455f2b6206cbfa1338c7afcf3b"
		},
		gameText: {
			file: "game-text.png",
			journey: "site-saved",
			title: "Investigate a shared source line",
			sha256: "39166602512ee6b7cbfe5c70d7fa56ad3990b8932705232ccedc731adee39a8e"
		},
		mapReview: {
			file: "map-review.png",
			journey: "map-review",
			title: "Review the colorful Camera Lab map",
			sha256: "a92aba65166095925c5132835a07c3258c552db06dfd5ecd5892934c35662ec5"
		},
		authoringCharts: {
			file: "authoring-charts.png",
			journey: "site-saved",
			title: "Chart the open DataTable",
			sha256: "727a9143cd7adfc6139e1db3e2c2bfc9d8c28c549a6f19e3a73a5d2e3dd0d63b"
		},
		configExplorer: {
			file: "config-explorer.png",
			journey: "site-saved",
			title: "Compare saved config across platforms",
			sha256: "54af97e092d338ccb3a2be61eca896f077babb13b81584bc76235113d48659aa"
		},
		configLineage: {
			file: "config-lineage.png",
			journey: "site-saved",
			title: "Trace the winning value",
			sha256: "04697ec43bbb2b4c1ce9547b9355fabca3922df69b5202b768e5c8a58c3fbcee"
		}
	},
	journeys: {
		"map-review": {
			recordingId: "20260927185707853-map-review-2ca25292",
			commit: "f27a5b4f",
			dirty: true,
			finishedAt: "2026-09-27T18:57:26.519Z"
		},
		"site-saved": {
			recordingId: "20260927163201217-site-saved-96a93739",
			commit: "f27a5b4",
			dirty: true,
			finishedAt: "2026-09-27T16:32:42.698Z"
		}
	}
} as const;
