import assert from "node:assert/strict";
import {
	cpSync,
	mkdirSync,
	mkdtempSync,
	readFileSync,
	readdirSync,
	rmSync,
	statSync,
	writeFileSync
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { retainLocalizationFixtureOutput } from "./localization-fixture-output.ts";

const committed = new URL(
	"../fixtures/unreal-project/FixtureExpected/localization/ue5.8-output/",
	import.meta.url
);

test("retains every generated byte and replaces only the selected version's snapshot", () => {
	const root = mkdtempSync(join(tmpdir(), "ue-shed-localization-output-"));
	try {
		const fixture = join(root, "fixture");
		const source = join(fixture, "Content", "Localization", "FixtureGame");
		cpSync(committed, source, { recursive: true });
		const evidence = join(root, "FixtureExpected", "localization");
		const previous = join(evidence, "ue5.7-output");
		mkdirSync(previous, { recursive: true });
		writeFileSync(join(previous, "keep.txt"), "Other version");
		const destination = retainLocalizationFixtureOutput(fixture, evidence, "5.8");
		assert.equal(destination, join(evidence, "ue5.8-output"));
		writeFileSync(join(destination, "obsolete.po"), "Stale snapshot file");
		retainLocalizationFixtureOutput(fixture, evidence, "5.8");
		const files = readdirSync(source, { recursive: true, encoding: "utf8" }).sort();
		assert.deepEqual(
			readdirSync(destination, { recursive: true, encoding: "utf8" }).sort(),
			files
		);
		for (const file of files) {
			if (!statSync(join(source, file)).isFile()) continue;
			assert.deepEqual(
				readFileSync(join(destination, file)),
				readFileSync(join(source, file))
			);
		}
		assert.equal(readFileSync(join(previous, "keep.txt"), "utf8"), "Other version");
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("rejects invalid versions and overlapping paths before replacing files", () => {
	const root = mkdtempSync(join(tmpdir(), "ue-shed-localization-output-"));
	try {
		const source = join(root, "Content", "Localization", "FixtureGame");
		mkdirSync(source, { recursive: true });
		const sentinel = join(source, "keep.txt");
		writeFileSync(sentinel, "Generated output");
		assert.throws(() => retainLocalizationFixtureOutput(root, root, "../5.8"), /version/);
		assert.throws(() => retainLocalizationFixtureOutput(root, source, "5.8"), /separate/);
		assert.equal(readFileSync(sentinel, "utf8"), "Generated output");
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});
