import { spawnSync } from "node:child_process";
import { globSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { Schema } from "effect";
import { siteMedia } from "../apps/site/src/showcase/media.ts";
import {
	checkSiteMedia,
	containedFile,
	exportPlan,
	prepareCaptures,
	RecordingManifest,
	SiteMedia,
	type Journey
} from "./site-media-model.ts";

const repositoryRoot = resolve(import.meta.dirname, "..");
const mediaDir = join(repositoryRoot, "apps/site/public/media");
const manifestPath = join(repositoryRoot, "apps/site/src/showcase/media.ts");
const args = process.argv.slice(2);
const pins = new Map<Journey, string>();
const selected = new Set<Journey>();
let resultsRoot = join(repositoryRoot, "test-results/showcase");
let check = false;

function journeyName(value: string | undefined): Journey {
	if (value === "site-saved" || value === "map-review") return value;
	throw new Error(`Unknown journey: ${value}. Choose ${Object.keys(exportPlan).join(", ")}.`);
}

for (let index = 0; index < args.length; index += 1) {
	const argument = args[index];
	if (argument === "--check") check = true;
	else if (argument === "--journey") selected.add(journeyName(args[++index]));
	else if (argument === "--bundle") {
		const [journey, id, extra] = (args[++index] ?? "").split("=");
		if (!id || extra || !/^[a-zA-Z0-9-]+$/.test(id))
			throw new Error("Use --bundle journey=recording-id");
		const name = journeyName(journey);
		pins.set(name, id);
		selected.add(name);
	} else if (argument === "--results-root") {
		const value = args[++index];
		if (!value || value.startsWith("--"))
			throw new Error("--results-root requires a directory");
		resultsRoot = resolve(value);
	} else throw new Error(`Unknown argument: ${argument}`);
}

if (check) {
	if (args.length !== 1) throw new Error("--check cannot be combined with export options");
	checkSiteMedia(Schema.decodeUnknownSync(SiteMedia)(siteMedia), mediaDir);
	process.stdout.write("Site screenshots and recording provenance verified.\n");
} else {
	if (selected.size === 0)
		for (const name of Object.keys(exportPlan)) selected.add(journeyName(name));
	const previous = Schema.decodeUnknownSync(SiteMedia)(siteMedia);
	const captures = { ...previous.captures };
	const journeys = { ...previous.journeys };
	const prepared: ReturnType<typeof prepareCaptures> = [];
	// Validate every requested bundle and chapter before touching any published asset.
	for (const journey of selected) {
		const recordingPattern = pins.get(journey) ?? `*-${journey}-*`;
		const candidates = globSync(`${recordingPattern}/**/run.json`, { cwd: resultsRoot })
			.map((path) => {
				const manifest = Schema.decodeUnknownSync(RecordingManifest)(
					JSON.parse(readFileSync(containedFile(resultsRoot, path), "utf8"))
				);
				return { manifest, path, recordingId: path.split(/[\\/]/)[0] };
			})
			.filter(
				({ manifest, recordingId }) =>
					manifest.journey === journey &&
					(pins.has(journey) ? recordingId === pins.get(journey) : true)
			)
			.sort((a, b) => b.manifest.finishedAt.localeCompare(a.manifest.finishedAt));
		// Never silently fall back to an older success when the latest run failed.
		const candidate = candidates[0];
		if (!candidate)
			throw new Error(`No ${journey} recording found. Run pnpm showcase:record ${journey}.`);
		const { manifest, path, recordingId } = candidate;
		const entries = prepareCaptures(join(resultsRoot, dirname(path)), manifest, journey);
		prepared.push(...entries);
		for (const { key, capture } of entries) captures[key] = capture;
		journeys[journey] = {
			recordingId,
			commit: manifest.commit,
			dirty: manifest.dirty,
			finishedAt: manifest.finishedAt
		};
	}
	for (const journey of Object.keys(journeys)) {
		if (!Object.values(captures).some((capture) => capture.journey === journey))
			delete journeys[journey];
	}
	const updated = { exportedAt: new Date().toISOString(), captures, journeys };
	checkSiteMedia(
		Schema.decodeUnknownSync(SiteMedia)(updated),
		mediaDir,
		new Map(prepared.map(({ bytes, capture }) => [capture.file, bytes]))
	);
	mkdirSync(mediaDir, { recursive: true });
	for (const { bytes, capture } of prepared) writeFileSync(join(mediaDir, capture.file), bytes);
	writeFileSync(
		manifestPath,
		`// GENERATED by scripts/site-media.ts — refresh with pnpm site:media.\nexport const siteMedia = ${JSON.stringify(updated, null, "\t")} as const;\n`
	);
	const formatted = spawnSync(
		process.platform === "win32" ? "pnpm.cmd" : "pnpm",
		["exec", "oxfmt", "--write", manifestPath],
		{
			cwd: repositoryRoot,
			shell: process.platform === "win32",
			stdio: "inherit",
			windowsHide: true
		}
	);
	if (formatted.status !== 0) process.exit(formatted.status ?? 1);
	checkSiteMedia(Schema.decodeUnknownSync(SiteMedia)(updated), mediaDir);
	process.stdout.write(
		`Exported ${prepared.length} screenshots. Review the images and commit them with the manifest.\n`
	);
}
