import { cleanup, fireEvent, render, screen, waitFor, within } from "@solidjs/testing-library";
import { userEvent } from "@testing-library/user-event";
import type {
	BlueprintGraphCoverageGap,
	BlueprintGraphProjection,
	BlueprintNode,
	BlueprintPin
} from "@ue-shed/protocol";
import { EffectRuntimeProvider } from "@ue-shed/ui";
import { Effect, Layer, ManagedRuntime } from "effect";
import { afterAll, afterEach, describe, expect, it, vi } from "vitest";
import type {
	BlueprintAssetCandidate,
	BlueprintGraphFailureReason,
	BlueprintGraphReadResult
} from "./contract.js";
import { BlueprintGraphViewer } from "./blueprint-graph-viewer.js";
import {
	ProjectBlueprintSearch,
	type ProjectBlueprintSearchProps
} from "./project-blueprint-search.js";

const runtime = ManagedRuntime.make(Layer.empty);
const assetPath = "C:/Project/Content/UI/WBP_Settings.uasset";
const searchLabel = "Search project Blueprints";
const indexedSettings: BlueprintAssetCandidate = {
	assetName: "WBP_Settings",
	assetPath,
	className: "WidgetBlueprint",
	packageName: "/Game/UI/WBP_Settings",
	relativePath: "Content/UI/WBP_Settings.uasset"
};
const indexedPlayer: BlueprintAssetCandidate = {
	assetName: "BP_PlayerCharacter",
	assetPath: "C:/Project/Content/Characters/BP_PlayerCharacter.uasset",
	className: "Blueprint",
	packageName: "/Game/Characters/BP_PlayerCharacter",
	relativePath: "Content/Characters/BP_PlayerCharacter.uasset"
};

const indexedProject = {
	assets: [indexedSettings],
	matchCount: 1,
	projectName: "ExampleProject",
	status: "ready" as const
};

// JSDOM has no layout, ResizeObserver or DOMMatrix. The real Solid Flow components still mount
// nodes and selection; handle geometry, edges and fitting need a browser. Solid Flow measures on
// timers that can outlive a test, so the stand-ins stay on this file's window instead of being
// stubbed per test. Node presses use fireEvent.click: d3-zoom's pane handler reads the pointer
// event's view, which user-event leaves null in JSDOM.
class NoLayoutResizeObserver {
	observe() {}
	unobserve() {}
	disconnect() {}
}
class IdentityMatrix {
	readonly m22 = 1;
}
Object.assign(window, {
	ResizeObserver: window.ResizeObserver ?? NoLayoutResizeObserver,
	DOMMatrixReadOnly: window.DOMMatrixReadOnly ?? IdentityMatrix
});

afterEach(cleanup);
afterAll(() => runtime.dispose());

function pin(input: {
	readonly category?: string;
	readonly defaultValue?: string;
	readonly direction: "input" | "output";
	readonly id: string;
	readonly linkedTo?: BlueprintPin["linked_to"];
	readonly name: string;
}): BlueprintPin {
	return {
		id: input.id,
		name: input.name,
		source_index: 0,
		tooltip: input.name === "bEnabled" ? "Whether the setting is enabled." : "",
		direction: input.direction,
		pin_type: {
			category: input.category ?? "exec",
			subcategory: "",
			container_type: "none",
			is_reference: false,
			is_weak_pointer: false,
			member_reference: { name: "" },
			is_const: false,
			is_uobject_wrapper: false,
			serialize_as_single_precision_float: false
		},
		default_value: input.defaultValue ?? "",
		autogenerated_default_value: "",
		linked_to: input.linkedTo ?? [],
		sub_pins: [],
		flags: 0
	};
}

function node(input: {
	readonly classPath: string;
	readonly kind: BlueprintNode["kind"];
	readonly objectPath: string;
	readonly pins: readonly BlueprintPin[];
	readonly title: string;
	readonly x: number;
	readonly y: number;
}): BlueprintNode {
	return {
		object_path: input.objectPath,
		class_path: input.classPath,
		kind: input.kind,
		title: input.title,
		position: { x: input.x, y: input.y },
		properties: [],
		pins: input.pins,
		subclass_tail_bytes: 0
	};
}

const eventPath = "/Game/UI/WBP_Settings.WBP_Settings:EventGraph.Event";
const callPath = "/Game/UI/WBP_Settings.WBP_Settings:EventGraph.Call";

const blueprint: BlueprintGraphProjection = {
	schema_version: 2,
	definition: {
		parent_class: null,
		variables: null,
		default_object: null,
		construction_script: null
	},
	object_path: "/Game/UI/WBP_Settings.WBP_Settings",
	coverage_gaps: [],
	graphs: [
		{
			object_path: "/Game/UI/WBP_Settings.WBP_Settings:EventGraph",
			name: "EventGraph",
			nodes: [
				node({
					classPath: "/Script/BlueprintGraph.K2Node_Event",
					kind: "event",
					objectPath: eventPath,
					pins: [
						pin({
							direction: "output",
							id: "event-out",
							linkedTo: [{ node_object_path: callPath, pin_id: "call-in" }],
							name: "then"
						})
					],
					title: "On Clicked",
					x: 0,
					y: 0
				}),
				node({
					classPath: "/Script/BlueprintGraph.K2Node_CallFunction",
					kind: "function_call",
					objectPath: callPath,
					pins: [
						pin({ direction: "input", id: "call-in", name: "execute" }),
						pin({
							category: "bool",
							defaultValue: "true",
							direction: "input",
							id: "enabled",
							name: "bEnabled"
						})
					],
					title: "Apply Settings With A Deliberately Long Saved Node Name",
					x: 360,
					y: 0
				})
			],
			links: [
				{
					from: { node_object_path: eventPath, pin_id: "event-out" },
					to: { node_object_path: callPath, pin_id: "call-in" }
				}
			]
		},
		{
			object_path: "/Game/UI/WBP_Settings.WBP_Settings:UtilityGraph",
			name: "A Utility Graph With A Very Long Saved Name",
			nodes: [
				node({
					classPath: "/Script/BlueprintGraph.K2Node_VariableGet",
					kind: "variable_get",
					objectPath: "/Game/UI/WBP_Settings.WBP_Settings:UtilityGraph.Value",
					pins: [
						pin({ category: "float", direction: "output", id: "value", name: "Value" })
					],
					title: "Saved Value",
					x: -420,
					y: 880
				})
			],
			links: []
		}
	]
};

function ready(projection: BlueprintGraphProjection = blueprint): BlueprintGraphReadResult {
	return {
		assetPath,
		blueprint: projection,
		diagnostics: [],
		outcome: "complete",
		status: "ready"
	};
}

type BlueprintViewerClient = Pick<
	ProjectBlueprintSearchProps,
	"readBlueprint" | "searchBlueprints"
>;

function renderViewer(client: BlueprintViewerClient) {
	return render(() => (
		<EffectRuntimeProvider runtime={runtime}>
			<BlueprintGraphViewer
				opener={(controls) => <ProjectBlueprintSearch controls={controls} {...client} />}
				transportFailureCopy={{
					title: "The local reader request failed",
					message: "The read request could not be completed.",
					recovery: "Retry the read request. Unreal is not required."
				}}
			/>
		</EffectRuntimeProvider>
	));
}

function clientWith(
	overrides: {
		readonly readBlueprint?: BlueprintViewerClient["readBlueprint"];
		readonly searchBlueprints?: BlueprintViewerClient["searchBlueprints"];
	} = {}
): BlueprintViewerClient {
	return {
		readBlueprint: overrides.readBlueprint ?? (() => Effect.succeed(ready())),
		searchBlueprints: overrides.searchBlueprints ?? (() => Effect.succeed(indexedProject))
	};
}

async function openPath() {
	await userEvent
		.setup()
		.click(await screen.findByRole("button", { name: "Open WBP_Settings from project index" }));
}

describe("BlueprintGraphViewer", () => {
	it("renders Flow nodes and selects their saved evidence in the inspector", async () => {
		render(() => (
			<EffectRuntimeProvider runtime={runtime}>
				<BlueprintGraphViewer
					initialRead={Effect.succeed(ready())}
					opener={() => undefined}
				/>
			</EffectRuntimeProvider>
		));
		const canvas = await screen.findByLabelText("Graph viewport");
		expect(await within(canvas).findByText("On Clicked")).toBeTruthy();
		const callNode = within(canvas).getByText(
			"Apply Settings With A Deliberately Long Saved Node Name"
		);
		expect(within(canvas).getByText("bEnabled")).toBeTruthy();
		fireEvent.click(callNode);
		const inspector = screen.getByRole("complementary", { name: "Inspector" });
		await waitFor(() => {
			expect(
				within(inspector).getByRole("heading", {
					name: "Apply Settings With A Deliberately Long Saved Node Name"
				})
			).toBeTruthy();
		});
		expect(within(inspector).getByText("Whether the setting is enabled.")).toBeTruthy();
	});

	it("inspects the already-selected node again from the keyboard", async () => {
		render(() => (
			<EffectRuntimeProvider runtime={runtime}>
				<BlueprintGraphViewer
					initialRead={Effect.succeed(ready())}
					opener={() => undefined}
				/>
			</EffectRuntimeProvider>
		));
		const selected = await screen.findByRole("button", { name: "Inspect On Clicked" });
		const user = userEvent.setup();
		await user.click(screen.getByRole("tab", { name: "Blueprint" }));
		expect(screen.getByRole("tab", { name: "Blueprint" }).getAttribute("aria-selected")).toBe(
			"true"
		);
		selected.focus();
		await user.keyboard("{Enter}");
		await waitFor(() =>
			expect(screen.getByRole("tab", { name: "Node" }).getAttribute("aria-selected")).toBe(
				"true"
			)
		);
		expect(screen.getByRole("heading", { name: "On Clicked" })).toBeTruthy();
	});

	it("opens a canned read through a custom opener without a project index", async () => {
		const opener = vi.fn(
			(controls: import("./blueprint-graph-viewer.js").BlueprintGraphOpenerControls) => (
				<button
					disabled={controls.loading}
					onClick={() => controls.open(Effect.succeed(ready()))}
				>
					Open uploaded Blueprint
				</button>
			)
		);
		render(() => (
			<EffectRuntimeProvider runtime={runtime}>
				<BlueprintGraphViewer opener={opener} />
			</EffectRuntimeProvider>
		));

		await userEvent
			.setup()
			.click(screen.getByRole("button", { name: "Open uploaded Blueprint" }));
		const summary = await screen.findByRole("region", { name: "Blueprint summary" });
		expect(within(summary).getByRole("heading", { name: "WBP_Settings" })).toBeTruthy();
		expect(
			within(summary).getByRole("button", { name: "Open uploaded Blueprint" })
		).toBeTruthy();
		expect(screen.queryByRole("searchbox", { name: searchLabel })).toBeNull();
		expect(opener).toHaveBeenCalledTimes(1);
	});

	it("accepts an initial read and lets a footer reveal another graph's node", async () => {
		render(() => (
			<EffectRuntimeProvider runtime={runtime}>
				<BlueprintGraphViewer
					initialRead={Effect.succeed(ready())}
					opener={() => undefined}
					footer={(_read, controls) => (
						<button
							onClick={() =>
								controls.reveal(
									"/Game/UI/WBP_Settings.WBP_Settings:UtilityGraph.Value"
								)
							}
						>
							Reveal footer reference
						</button>
					)}
				/>
			</EffectRuntimeProvider>
		));
		await userEvent
			.setup()
			.click(await screen.findByRole("button", { name: "Reveal footer reference" }));
		expect(
			screen
				.getByRole("tab", { name: /A Utility Graph With A Very Long Saved Name/ })
				.getAttribute("aria-selected")
		).toBe("true");
		expect(screen.getByRole("heading", { name: "Saved Value" })).toBeTruthy();
	});

	it("searches saved nodes and pins across graphs and selects their owning node", async () => {
		renderViewer(clientWith());
		await openPath();
		const user = userEvent.setup();
		const search = screen.getByLabelText("Search saved nodes and pins");
		await user.type(search, "Saved Value");
		await user.click(screen.getByRole("button", { name: "node · Saved Value" }));
		expect(screen.getByRole("heading", { name: "Saved Value" })).toBeTruthy();
		await user.clear(search);
		await user.type(search, "bEnabled");
		await user.click(screen.getByRole("button", { name: "pin · bEnabled" }));
		expect(screen.getByRole("heading", { name: /Apply Settings With/ })).toBeTruthy();
	});

	it("searches the selected project's saved package index and opens a result", async () => {
		const readBlueprint = vi.fn((_path: string) => Effect.succeed(ready()));
		const searchBlueprints = vi.fn((request: { readonly query: string }) => {
			const assets = request.query.toLowerCase().includes("settings")
				? [indexedSettings]
				: [indexedPlayer, indexedSettings];
			return Effect.succeed({
				assets,
				matchCount: assets.length,
				projectName: "ExampleProject",
				status: "ready" as const
			});
		});
		renderViewer(clientWith({ readBlueprint, searchBlueprints }));

		expect(
			await screen.findByRole("button", {
				name: "Open WBP_Settings from project index"
			})
		).toBeDefined();
		const user = userEvent.setup();
		await user.type(screen.getByLabelText(searchLabel), "settings");
		await waitFor(() =>
			expect(searchBlueprints).toHaveBeenLastCalledWith({ query: "settings" })
		);
		expect(
			screen.queryByRole("button", {
				name: "Open BP_PlayerCharacter from project index"
			})
		).toBeNull();

		await user.keyboard("{Enter}");
		await waitFor(() => expect(readBlueprint).toHaveBeenCalledWith(assetPath));
		expect(await screen.findByText("Fully decoded")).toBeDefined();
		expect(screen.getByLabelText<HTMLInputElement>(searchLabel).value).toBe("");
		await waitFor(() => expect(searchBlueprints).toHaveBeenLastCalledWith({ query: "" }));
	});

	it("searches only the scanned project and defers project selection to the sidebar", async () => {
		renderViewer(
			clientWith({ searchBlueprints: () => Effect.succeed({ status: "not_configured" }) })
		);

		expect(await screen.findByRole("heading", { name: "No project selected" })).toBeDefined();
		expect(screen.queryByRole("button", { name: /Choose project|Browse|^Open$/ })).toBeNull();
		expect(screen.queryByLabelText(searchLabel)).toBeNull();
	});

	it("keeps the project index one keystroke away after a Blueprint is open", async () => {
		const readBlueprint = vi.fn((_path: string) => Effect.succeed(ready()));
		renderViewer(
			clientWith({
				readBlueprint,
				searchBlueprints: () =>
					Effect.succeed({
						assets: [indexedPlayer, indexedSettings],
						matchCount: 2,
						projectName: "ExampleProject",
						status: "ready" as const
					})
			})
		);
		await openPath();
		expect(await screen.findByText("Fully decoded")).toBeDefined();
		expect(
			screen.queryByRole("button", { name: "Open BP_PlayerCharacter from project index" })
		).toBeNull();

		const user = userEvent.setup();
		await user.type(screen.getByLabelText(searchLabel), "player");
		await user.keyboard("{ArrowDown}");
		expect(document.activeElement?.getAttribute("aria-label")).toBe(
			"Open BP_PlayerCharacter from project index"
		);
		await user.keyboard("{Enter}");
		await waitFor(() =>
			expect(readBlueprint).toHaveBeenLastCalledWith(indexedPlayer.assetPath)
		);
	});

	it("opens an indexed Blueprint and exposes saved topology, pin types, and defaults", async () => {
		const readBlueprint = vi.fn((_path: string) => Effect.succeed(ready()));
		renderViewer(clientWith({ readBlueprint }));

		await openPath();

		await waitFor(() => expect(readBlueprint).toHaveBeenCalledWith(assetPath));
		expect(await screen.findByText("Fully decoded")).toBeDefined();
		expect(screen.queryByLabelText("Projection coverage")).toBeNull();
		expect(await screen.findByRole("button", { name: "Inspect On Clicked" })).toBeDefined();

		fireEvent.click(
			screen.getByRole("button", {
				name: "Inspect Apply Settings With A Deliberately Long Saved Node Name"
			})
		);
		const pins = await screen.findByLabelText("Saved pin evidence");
		expect(within(pins).getByText("bool")).toBeDefined();
		expect(within(pins).getByText("Saved default")).toBeDefined();
		expect(within(pins).getByText("true")).toBeDefined();
		expect(within(pins).getByText("Whether the setting is enabled.")).toBeDefined();
	});

	it("shows native partial evidence even when topology coverage has no gaps", async () => {
		renderViewer(
			clientWith({
				readBlueprint: (assetPath) =>
					Effect.succeed({
						assetPath,
						blueprint,
						diagnostics: [
							{
								code: "unsupported_format",
								message: "One node payload remains only partially decoded.",
								severity: "warning" as const
							}
						],
						outcome: "partial" as const,
						status: "ready" as const
					})
			})
		);

		await openPath();

		expect(await screen.findByText("Topology complete; projection partial")).toBeDefined();
		expect(screen.getByText("Topology complete")).toBeDefined();
		expect(screen.getByLabelText("Blueprint decode diagnostics")).toBeDefined();
		expect(screen.getByText("One node payload remains only partially decoded.")).toBeDefined();
	});

	it("switches graphs and changes zoom", async () => {
		renderViewer(clientWith());
		const user = userEvent.setup();

		await openPath();
		expect(await screen.findByText("Fully decoded")).toBeDefined();

		await user.click(
			screen.getByRole("tab", {
				name: "A Utility Graph With A Very Long Saved Name, 1 node"
			})
		);
		expect(await screen.findByRole("button", { name: "Inspect Saved Value" })).toBeDefined();
		const zoom = () =>
			Number.parseInt(screen.getByLabelText("Graph zoom").textContent ?? "", 10);
		await user.click(screen.getByRole("button", { name: "1:1" }));
		await waitFor(() => expect(zoom()).toBe(100));
		await user.click(screen.getByRole("button", { name: "Zoom in" }));
		await waitFor(() => expect(zoom()).toBeGreaterThan(100));
		await user.click(screen.getByRole("button", { name: "1:1" }));
		await user.click(screen.getByRole("button", { name: "Zoom out" }));
		await waitFor(() => expect(zoom()).toBeLessThan(100));
	});

	it("reports loading while a saved package is decoded", async () => {
		renderViewer(clientWith({ readBlueprint: () => Effect.never }));
		await openPath();
		expect(await screen.findByText("Reading saved package")).toBeDefined();
		expect(screen.queryByRole("alert")).toBeNull();
	});

	it("treats a graphless Blueprint as valid saved-package evidence", async () => {
		renderViewer(
			clientWith({
				readBlueprint: () => Effect.succeed(ready({ ...blueprint, graphs: [] }))
			})
		);
		await openPath();

		expect(
			await screen.findByRole("heading", { name: "No saved editor graphs" })
		).toBeDefined();
		expect(screen.getByText(/valid graphless result/)).toBeDefined();
		expect(screen.getByRole("tab", { name: "Blueprint", selected: true })).toBeDefined();
		expect(screen.getByLabelText("Blueprint definition")).toBeDefined();
		expect(within(screen.getByLabelText("Blueprint summary")).getAllByText("0")).toHaveLength(
			4
		);
	});

	it("distinguishes metadata-only gaps from incomplete topology", async () => {
		const metadataGap: BlueprintGraphCoverageGap = {
			object_path: callPath,
			reason: "native_node_subclass_tail",
			detail: "24 native subclass bytes remain opaque"
		};
		renderViewer(
			clientWith({
				readBlueprint: () =>
					Effect.succeed(ready({ ...blueprint, coverage_gaps: [metadataGap] }))
			})
		);
		await openPath();

		expect(
			await screen.findByText("Topology complete; specialized metadata partial")
		).toBeDefined();
		expect(screen.getByText(/does not mean graph links are missing/)).toBeDefined();
		await userEvent.setup().click(screen.getByText("1 coverage gap"));
		expect(screen.getByText("24 native subclass bytes remain opaque")).toBeDefined();
	});

	it("labels unresolved saved references as partial topology", async () => {
		const topologyGap: BlueprintGraphCoverageGap = {
			object_path: eventPath,
			reason: "unresolved_linked_pin",
			detail: "Linked pin owner was not decoded"
		};
		renderViewer(
			clientWith({
				readBlueprint: () =>
					Effect.succeed(ready({ ...blueprint, coverage_gaps: [topologyGap] }))
			})
		);
		await openPath();

		expect(await screen.findByText("Partial saved-graph projection")).toBeDefined();
		expect(screen.getByText("Topology partial")).toBeDefined();
		expect(screen.getByText(/topology may be incomplete/)).toBeDefined();
	});

	it("keeps a dense, widely positioned graph inspectable", async () => {
		const denseNodes = Array.from({ length: 24 }, (_, index) =>
			node({
				classPath: "/Script/BlueprintGraph.K2Node_CallFunction",
				kind: "function_call",
				objectPath: `/Game/UI/BP_Dense.BP_Dense:EventGraph.Node_${index}`,
				pins: [
					pin({ direction: "input", id: `in-${index}`, name: "execute" }),
					pin({ direction: "output", id: `out-${index}`, name: "then" })
				],
				title:
					index === 23
						? "Final Dense Node With A Deliberately Long Saved Evidence Name"
						: `Dense Node ${index}`,
				x: (index % 6) * 520 - 900,
				y: Math.floor(index / 6) * 380 - 600
			})
		);
		const denseLinks = denseNodes.flatMap((source, index) => {
			const target = denseNodes[index + 1];
			return target === undefined
				? []
				: [
						{
							from: { node_object_path: source.object_path, pin_id: `out-${index}` },
							to: {
								node_object_path: target.object_path,
								pin_id: `in-${index + 1}`
							}
						}
					];
		});
		renderViewer(
			clientWith({
				readBlueprint: () =>
					Effect.succeed(
						ready({
							...blueprint,
							graphs: [
								{
									links: denseLinks,
									name: "Dense Event Graph",
									nodes: denseNodes,
									object_path: "/Game/UI/BP_Dense.BP_Dense:EventGraph"
								}
							]
						})
					)
			})
		);
		await openPath();

		expect(within(screen.getByLabelText("Blueprint summary")).getByText("24")).toBeDefined();
		// Every saved node mounts as an inspectable Flow node, however far apart they were saved.
		const canvas = screen.getByLabelText("Graph viewport");
		await waitFor(() =>
			expect(
				within(canvas).getAllByRole("button", { name: /^Inspect Dense Node/ })
			).toHaveLength(23)
		);
		fireEvent.click(
			screen.getByRole("button", {
				name: "Inspect Final Dense Node With A Deliberately Long Saved Evidence Name"
			})
		);
		await waitFor(() =>
			expect(
				screen.getByRole("heading", {
					name: "Final Dense Node With A Deliberately Long Saved Evidence Name"
				})
			).toBeDefined()
		);
	});

	it.each<readonly [BlueprintGraphFailureReason, string]>([
		["unsupported_version", "This saved package revision is unsupported"],
		["control_rig", "Control Rig uses a different graph model"],
		["malformed_package", "The saved package is malformed"],
		["missing_reader", "The local UAsset reader is unavailable"]
	])("renders the %s recovery state", async (reason, title) => {
		renderViewer(
			clientWith({
				readBlueprint: () =>
					Effect.succeed({
						assetPath,
						message: `Reader reported ${reason}.`,
						reason,
						recovery: "Use the safe recovery for this state.",
						status: "failed"
					})
			})
		);
		await openPath();

		const alert = await screen.findByRole("alert");
		expect(alert.textContent).toContain(title);
		expect(alert.textContent).toContain("Use the safe recovery");
		const message = within(alert).getByText(`Reader reported ${reason}.`);
		const recovery = within(alert).getByText("Use the safe recovery for this state.");
		expect(message.tagName).toBe("P");
		expect(recovery.tagName).toBe("P");
		expect(message).not.toBe(recovery);
	});

	it("places host recovery actions inside the package failure callout", async () => {
		render(() => (
			<EffectRuntimeProvider runtime={runtime}>
				<BlueprintGraphViewer
					opener={() => undefined}
					initialRead={Effect.succeed<BlueprintGraphReadResult>({
						status: "failed",
						reason: "unsupported_asset",
						message: "This file contains no saved Blueprint editor graph",
						recovery: "Choose an uncooked Blueprint .uasset."
					})}
					failureActions={(failure) =>
						failure.reason === "unsupported_asset" ? (
							<a href="/inspect">Inspect this file instead</a>
						) : undefined
					}
				/>
			</EffectRuntimeProvider>
		));
		const alert = await screen.findByRole("alert");
		const action = within(alert).getByRole("link", { name: "Inspect this file instead" });
		expect(action.getAttribute("href")).toBe("/inspect");
		expect(within(alert).getByText("Choose an uncooked Blueprint .uasset.").tagName).toBe("P");
	});

	it("keeps renderer transport failures distinct from package failures", async () => {
		renderViewer(
			clientWith({
				readBlueprint: () => Effect.fail("Host transport unavailable")
			})
		);
		await openPath();

		const alert = await screen.findByRole("alert");
		expect(alert.textContent).toContain("local reader request failed");
		expect(alert.textContent).toContain("Unreal is not required");
	});
});
